# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


loveOnTopLyrics = <<-LOVEONTOPLYRICS
BA BA BADA
BA BA BADA 
BA BA BADA 
BA BA BADA 
BA BA BADA 
BA BA BADA 
BA BA BADA 
BRING THE BEAT IN
HONEY HONEY, I CAN SEE THE STARS ALL THE WAY FROM HERE CAN'T YOU SEE THE GLOW ON THE WINDOW PANE I CAN FEEL THE SUN WHENEVER YOU'RE NEAR EVERY TIME YOU TOUCH ME I JUST MELT AWAY
NOW EVERYBODY ASKS ME WHY I'M SMILING OUT FROM EAR TO EAR THEY SAY LOVE HURTS BUT I KNOW, IT'S GONNA' TAKE A LITTLE WORK OHH, NOTHING'S PERFECT, BUT IT'S WORTH IT AFTER FIGHTIN' THROUGH MY TEARS_AND FINALLY YOU PUT ME FIRST
BABY IT'S YOU YOU'RE THE ONE I LOVE YOU'RE THE ONE I NEED YOU'RE THE ONLY ONE I SEE 
COME ON BABY IT'S YOU YOU'RE THE ONE THAT GIVES YOUR ALL YOU'RE THE ONE I CAN ALWAYS CALL WHEN I NEED YOU MAKE EVERYTHING STOP FINALLY, YOU PUT MY LOVE ON TOP
OHHH, COME ON BABY YOU PUT MY LOVE ON TOP, TOP, TOP, TOP, TOP YOU PUT MY LOVE ON TOP OHH OHHH, COME ON BABY YOU PUT MY LOVE TOP, TOP, TOP, TOP, TOP PUT MY LOVE ON TOP, PUT MY LOVE ON TOP
BABY BABY I CAN HEAR THE WIND WHIPPING PAST MY FACE AS WE DANCE THE NIGHT AWAY BOY YOUR LIPS TASTE LIKE A NIGHT OF CHAMPAGNE AS I KISS YOU AGAIN AND AGAIN AND AGAIN AND AGAIN
NOW EVERYBODY ASKS ME WHY I'M SMILING OUT FROM EAR TO EAR THEY SAY LOVE HURTS BUT I KNOW, IT'S GONNA TAKE A LITTLE WORK OHHH, NOTHINGS PERFECT, BUT IT'S WORTH IT AFTER FIGHTIN' THROUGH MY TEARS AND FINALLY YOU PUT ME FIRST
BABY IT'S YOU YOU'RE THE ONE I LOVE YOU'RE THE ONE I NEED YOU'RE THE ONLY ONE I SEE
COME ON BABY IT'S YOU YOU'RE THE ONE THAT GIVES YOUR ALL YOU'RE THE ONE THAT I CAN ALWAYS CALL WHEN I NEED TO MAKE EVERYTHING STOP FINALLY, YOU PUT MY LOVE ON TOP
OHHH, BABY YOU PUT MY LOVE ON TOP, TOP, TOP, TOP, TOP YOU PUT MY LOVE ON TOP OHH OHHH, COME ON BABY YOU PUT MY LOVE ON TOP, TOP, TOP, TOP, TOP PUT MY LOVE ON TOP
BABY IT'S YOU YOU'RE THE ONE I LOVE YOU'RE THE ONE I NEED YOU'RE THE ONLY THING I SEE
COME ON BABY IT'S YOU YOU'RE THE ONE THAT GIVES YOUR ALL YOU'RE THE ONE THAT ALWAYS CALLS WHEN I NEED YOU BABY EVERYTHING STOPS FINALLY, YOU PUT MY LOVE ON TOP
BABY YOU'RE THE ONE THAT I LOVE BABY YOU'RE ALL I NEED YOU'RE THE ONLY ONE I SEE COME ON BABY IT'S YOU YOU'RE THE ONE THAT GIVES YOUR ALL YOU'RE THE ONE THAT ALWAYS CALLS WHEN I NEED YOU EVERYTHING STOPS FINALLY, YOU PUT MY LOVE ON TOP
BABY 'CAUSE YOU'RE THE ONE THAT I LOVE BABY YOU'RE THE ONE THAT I NEED YOU'RE THE ONLY MAN I SEE
BABY, BABY IT'S YOU YOU'RE THE ONE THAT GIVES YOUR ALL YOU'RE THE ONE THAT ALWAYS CALLS WHEN I NEED YOU EVERYTHING STOPS FINALLY, YOU PUT MY LOVE ON TOP
BABY 'CAUSE YOU'RE THE ONE THAT I LOVE BABY YOU'RE THE ONE THAT I NEED YOU'RE THE ONLY ONE I SEE
BABY, BABY IT'S YOU YOU'RE THE ONE THAT GIVES YOUR ALL YOU'RE THE ONE THAT ALWAYS CALLS WHEN I NEED YOU EVERYTHING STOPS FINALLY, YOU PUT MY LOVE ON TOP
LOVEONTOPLYRICS

partyLyrics = <<-PARTYLYRICS
YOU A BAD GIRL AND YOUR FRIEND’S BAD TOO, OOH
WE GOT THE SWAG SAUCE, SHE DRIPPIN SWAGU YOU A BAD GIRL AND YOUR FRIEND’S BAD TOO, OOH WE GOT THE SWAG SAUCE, SHE DRIPPIN SWAGU OOH
I MAY BE YOUNG, BUT I’M READY TO GIVE YOU ALL MY LOVE I TOLD MY GIRLS YOU CAN GET IT DON’T SLOW IT DOWN, JUST LET IT GO
SO IN LOVE, I’LL GIVE IT ALL AWAY JUST DON’T TELL NOBODY TOMORROW SO TONIGHT, I’LL DO IT EVERY WAY SPEAKERS KNOCKIN’ TILL THE MORNING LIGHT
’CAUSE WE LIKE TO PARTY, AY…. (WE LIKE TO PARTY…)’CAUSE WE LIKE TO PARTY, AY…. (WE LIKE TO PARTY…) ’CAUSE WE LIKE TO PARTY
YOUR TOUCH IS DRIVIN’ ME CRAZY, I CAN’T EXPLAIN THE WAY I FEEL TOP DOWN WITH THE RADIO ON AND THE NIGHT BELONGS TO US JUST HOLD ME CLOSE, DON’T LET ME GO
SO IN LOVE, I DON’T CARE WHAT THEY SAY I DON’T CARE IF THEY TALKIN’ TOMORROW ’CAUSE TONIGHT’S THE NIGHT, OH OH OH OH THAT I’LL GIVE YOU EVERYTHING MUSIC KNOCKIN’ TILL THE MORNING LIGHT ’CAUSE WE LIKE TO PARTY
SET THE SCENE ... 3000 DEGREES I AIN'T WORRIED ’BOUT THEM OVER THERE BUT THEY WORRIED ’BOUT ME I GOTTA HOMEBOY NAMED BUTTER AND ANOTHER HOMEBOY THIS NAMED CHEESE WIT' ME BABY, I'LL MAKE IT MILK TILL IT DRIP DOWN YOUR KNEES SPIT THAT ISH FOR REAL-LO
BRAIN BRILLO'D KIDDO SAYS HE LOOKS UP TO ME THIS JUST MAKES ME FEEL OLD NEVER THOUGHT THAT WE COULD BECOME SOMEONE ELSE'S HERO MAN, WE WERE JUST IN THE FOOD COURT EATING OUR GYROS YESTERDAY THAT'S THE WAY EVERY SINGLE MORNING I TRY TO PRAY GRANDMAMMA ’DEM THEY NEVER FORGOT NOTHING ELSE REALLY MEAN NOTHING TO ME I AIN'T STUDDIN' THE BEAT TALKIN' TO ME? GIRL, WHY YOU WIT' ME? MOVE ON AIN'T NUTTIN TO SEE SHHH ALWAYS SUM'N TO SAW I'M THE RAW OF THE RIP ’CAUSE OF HIM ALL OF THEM WILL REMEMBER THE MIN
NUTE THEY FELL IN LOVE WITH RAP BLACK LIKE HAVING YO' COUSIN BACK BLUE LIKE WHEN THEY RENT IS DUE CREAM LIKE WHEN I'M LOVIN' YOU, YEEAAH
SO IN LOVE, I’LL GIVE IT ALL AWAY JUST DON’T TELL NOBODY TOMORROW ’CAUSE TONIGHT’S THE NIGHT, OH OH OH OH THAT I’LL GIVE YOU EVERYTHING MUSIC KNOCKIN’ TILL THE MORNING LIGHT ’CAUSE WE LIKE TO PARTY, AY…. (WE LIKE TO PARTY…) ’CAUSE WE LIKE TO PARTY, AY…. (WE LIKE TO PARTY…) ’CAUSE WE LIKE TO PARTY
YOU A BAD GIRL AND YOUR FRIENDS’ BAD TOO, OOH WE GOT THE SWAG SAUCE SHE DRIPPIN SWAGU YOU A BAD GIRL AND YOUR FRIENDS’ BAD TOO, OOH WE GOT THE SWAG SAUCE SHE DRIPPIN SWAGU OOH
PARTYLYRICS

schoolinLifeLyrics = <<-SCHOOLINLIFELYRICS
THIS IS FOR THEM TWENTY-SOMETHIN’S
TIME REALLY MOVES FAST YOU WERE JUST SIXTEEN

THIS IS FOR THEM THIRTY-SOMETHIN’S 
THAT DIDN’T TURN OUT EXACTLY HOW YOUR MOM AND DAD WANTED YOU TO BE

THIS IS FOR THEM FORTY-SOMETHIN’S 
WELL RAISE UP YOUR GLASS AND LAUGH LIKE A MUTHA

THIS IS FOR THEM FIFTY-SOMETHIN’S
HELL YOU’RE HALFWAY THERE BABY TAKE IT TO THE HEAD

MOM AND DAD TRIED TO HIDE THE WORLD
SAID THE WORLD’S JUST TOO BIG FOR A LITTLE GIRL
EYES WIDE OPEN, CAN’T YOU SEE 
I HAD MY FIRST HEELS BY THE AGE OF THIRTEEN

MOM AND DAD TRIED TO HIDE THE BOYS 
I SWEAR THAT JUST MADE ’EM WANT ME MORE
AT FOURTEEN THEY ASKED ME WHAT I WANT TO BE
I SAID BABY TWENTY-ONE, SO I GET ME A DRINK

I’M NOT A TEACHER, BABE BUT, I CAN TEACH YOU SOMETHING
I’M NOT A PREACHER, BUT WE CAN PRAY IF YOU WANNA
AIN’T A DOCTOR, BUT I CAN MAKE YOU FEEL BETTER 
BUT I’M GREAT AT WRITING PHYSICAL LOVE LETTERS

I’M A FREAK ALL DAY, A-A-ALL NIGHT 
HOT TOP FLIGHT, BOY YOU’RE OUTTA SIGHT
AND I’M CRAZY ALL DAY, A-A-ALL NIGHT 
WHO NEEDS A DEGREE WHEN YOU’RE SCHOOLIN’ LIFE

OH OH, OH OH, OH-OH OHH OHH
OH OH, OH OH, OH-OH OHH OHH 
SCHOOLIN’ LIFE
OH OH, OH OH, OH-OH OHH OHH
OH OH, OH OH, OH-OH OHH OHH
SCHOOLIN’ LIFE

THIS IS FOR THEM PRETTY-SOMETHIN’S 
LIVIN IN THE FAST LANE, SEE YOU WHEN YOU CRASH BABE

THIS IS FOR THEM SEXY-SOMETHIN’S 
THAT BODY AIN’T GON’ ALWAYS GET YOU OUT OF EVERYTHING

THIS IS FOR THEM BITTER-SOMETHIN’S 
STOP LIVIN’ IN REGRET, BABY IT’S NOT OVER YET

THIS IS FOR THEM CHIPPER-SOMETHIN’S 
THAT’S HIGH ON LIFE, BABY PUT ME ON YOUR FLIGHT

I’M NOT A TEACHER, BABY BUT, I CAN TEACH YOU SOMETHING 
NOT A PREACHER, BUT WE CAN PRAY IF YOU WANNA
AIN’T A DOCTOR, BUT I CAN MAKE YOU FEEL BETTER
BUT I’M GREAT AT WRITING PHYSICAL LOVE LETTERS

I’M A FREAK ALL DAY, A-A-ALL NIGHT 
HOT TOP TIGHT, BOY I’M OUTTA SIGHT
AND I’M CRAZY ALL DAY, A-A-ALL NIGHT
WHO NEEDS A DEGREE WHEN YOU’RE SCHOOLIN’ LIFE

OH OH, OH OH, OH-OH OHH OHH
OH OH, OH OH, OH-OH OHH OHH 
SCHOOLIN’ LIFE
OH OH, OH OH, OH-OH OHH OHH
OH OH, OH OH, OH-OH OHH OHH 
SCHOOLIN’ LIFE

YOU KNOW IT COST TO BE THE BOSS, ONE DAY YOU’LL RUN THE TOWN
FOR NOT MAKIN’ LIFE THAT YOU DECIDE
BABY PARTY TILL THE FIRE MARSHALL SHUT THIS SUCKA DOWN

I’M NOT A TEACHER, BABY BUT, I CAN TEACH YOU SOMETHING
NOT A PREACHER, BUT WE CAN PRAY IF YOU WANNA 
AIN’T A DOCTOR, BUT I CAN MAKE YOU FEEL BETTER
BUT I’M GREAT AT WRITING PHYSICAL LOVE LETTERS

I’M A FREAK ALL DAY, A-A-ALL NIGHT
HOT TOP TIGHT, BOY I’M OUTTA SIGHT
AND I’M CRAZY ALL DAY, A-A-ALL NIGHT
WHO NEEDS A DEGREE WHEN YOU’RE SCHOOLIN’ LIFE

OH OH, OH OH, OH-OH OHH OHH
OH OH, OH OH, OH-OH OHH OHH
WHO NEEDS A DEGREE WHEN YOU’RE SCHOOLIN’ LIFE 
OH OH, OH OH, OH-OH OHH OHH 
OH OH, OH OH, OH-OH OHH OHH 
WHO NEEDS A DEGREE WHEN YOU’RE SCHOOLIN’ LIFE

THERE’S NOT A REAL WAY TO LIVE THIS, FOR REAL 
JUST REMEMBER TO STAY RELENTLESS, OH YEAH, OH YEAH
DON’T STOP RUNNING UNTIL IT’S FINISHED, YEAH YEAH YEAH
IT’S UP TO YOU THE REST IS UNWRITTEN, YEAH, YEAH, YEAH
SCHOOLINLIFELYRICS

countdownLyrics = <<-COUNTDOWNLYRICS
BOY, OHHH KILLING ME SOFTLY AND I’M STILL FALLIN’ STILL THE ONE I NEED I WILL ALWAYS BE WITH YOU 
WHOA YOU GOT ME ALL GONE DON’T EVER LET ME GO SAY IT REAL LOUD IF YOU FLY IF YOU LEAVE ME YOU OUTTA YOUR MIND 
MY BABY IS A TEN WE DRESSIN’ TO THE NINE HE PICK ME UP WE EIGHT HE MAKE ME FEEL SO LUCKY SEVEN HE KISS ME IN HIS SIX WE BE MAKIN’ LOVE IN FIVE STILL THE ONE I DO THIS FOUR I’M TRYING TO MAKE US THREE FROM THA TWO HE’S STILL THE ONE 
THERE’S UPS AND DOWNS IN THIS LOVE GOT A LOT TO LEARN IN THIS LOVE THROUGH THE GOOD AND THE BAD STILL GOT LOVE DEDICATED TO THE ONE I LOVE, HEY 
STILL LOVE THE WAY HE TALKS STILL LOVE THE WAY I SANG STILL LOVE THE WAY HE ROCK THEM BLACK DIAMONDS IN THAT CHAIN STILL ALL UP ON EACH OTHER, AIN’T A DAMN THING CHANGED MY GIRLS CAN’T TELL ME NOTHING I’M A GONE IN THE BRAIN I’M ALL UP UNDER HIM LIKE IT’S COLD, WINTER TIME ALL UP IN THE KITCHEN IN MY HEELS, DINNER TIME DO WHATEVER THAT IT TAKES, YOU GOTTA WIN HIS MIND GIVE IT ALL TO HIM, AND MEET HIM AT THE FINISH LINE 
ME AND MY BOO, AND MY BOO, BOO, RIDIN’ ALL UP IN THE BLACK WITH HIS CHICK RIGHT BESIDE HIM LADIES IF YOU LOVE YOUR MAN, SHOW HIM YOU’RE THE FLYEST GRIND UP ON IT GIRL, SHOW HIM HOW YOU RIDE IT (2X) 
OHHH KILLING ME SOFTLY AND I’M STILL FALLIN’ STILL THE ONE I NEED I WILL ALWAYS BE WITH YOU 
WHOA YOU GOT ME ALL GONE DON’T EVER LET ME GO SAY IT REAL LOUD IF YOU FLY IF YOU EVER LEAVE ME YOU’RE OUTTA YOUR MIND 
MY BABY IS A TEN WE DRESSIN’ TO THE NINE HE PICK ME UP WE EIGHT HE MAKE ME FEEL SO LUCKY SEVEN HE KISS ME IN HIS SIX WE BE MAKIN’ LOVE IN FIVE STILL THE ONE I DO THIS FOUR I’M TRYING TO MAKE US THREE FROM THA TWO HE’S STILL THE ONE 
YEP I PUT IT ON ’EM, IT AIN’T NOTHING THAT I CAN’T DO YEP I BUY MY OWN, IF HE DESERVE IT BUY HIS SHIT TOO ALL UP IN THE STORE SHAWTY TRICKIN’ IF I WANT TO ALL UP IN THE STORE SHAWTY FLY AS WE WANT TO OOOO, DAMN I THINK I LOVE THAT BOY, DO ANYTHING FOR THAT BOY OOOO, NOW I’LL NEVER BE THE SAME, IT’S YOU AND ME UNTIL THE END 
ME AND MY BOO, AND MY BOO, BOO, RIDIN’ ALL UP IN THE BLACK WITH HIS CHICK RIGHT BESIDE HIM LADIES IF YOU LOVE YOUR MAN SHOW HIM YOU’RE THE FLYEST GRIND UP ON IT GIRL, SHOW HIM HOW YOU RIDE IT ME AND MY BOO, AND MY BOO LIP LOCKIN’ ALL UP IN THE BACK ’CAUSE THE CHICKS KEEP BLOCKIN’ ALL THAT GOSSIP BEEN TEN YEARS STOP IT LONDON SPEED IT UP, HOUSTON ROCK IT 
OHHH KILLING ME SOFTLY AND I’M STILL FALLIN’ STILL THE ONE I NEED I WILL ALWAYS BE WITH YOU 
WHOA YOU GOT ME ALL GONE DON’T EVER LET ME GO SAY IT REAL LOUD IF YOU FLY IF YOU EVER LEAVE ME YOU’RE OUTTA YOUR MIND 
MY BABY IS A TEN WE DRESSIN’ TO THE NINE HE PICK ME UP WE EIGHT HE MAKE ME FEEL SO LUCKY SEVEN HE KISS ME IN HIS SIX WE BE MAKIN’ LOVE IN FIVE STILL THE ONE I DO THIS FOUR I’M TRYING TO MAKE US THREE FROM THA TWO HE’S STILL THE ONE
COUNTDOWNLYRICS

iMissYouLyrics = <<-IMISSYOULYRICS
I THOUGHT THAT THINGS LIKE THIS GET BETTER WITH TIME
BUT I STILL NEED YOU, WHY IS THAT
YOU’RE THE ONLY IMAGE IN MY MIND
SO I STILL SEE YOU, AROUND

I MISS YOU, LIKE EVERYDAY
WANNA BE WITH YOU, BUT YOU’RE AWAY
SAID I MISS YOU, MISSING YOU INSANE
BUT IF I GOT WITH YOU, COULD IT FEEL THE SAME

THE WORDS DON’T EVER SEEM TO COME OUT RIGHT
BUT I STILL MEAN ’EM, WHY IS THAT
IT HURTS MY PRIDE TO TELL YOU HOW I FEEL
BUT I STILL NEED TO, WHY IS THAT

I MISS YOU, LIKE EVERYDAY
WANNA BE WITH YOU, BUT YOU’RE AWAY
SAID I MISS YOU, MISSING YOU INSANE
BUT IF I GOT WITH YOU, COULD IT FEEL THE SAME

IT DON’T MATTER WHO YOU ARE
IT IS SO SIMPLE, A FEELING, BUT IT’S EVERYTHING
NO MATTER WHO YOU LOVE
IT IS SO SIMPLE, A FEELING, BUT IT’S EVERYTHING

I MISS YOU, LIKE EVERYDAY
WANNA BE WITH YOU, BUT YOU’RE AWAY
SAID I MISS YOU, MISSING YOU INSANE
BUT IF I GOT WITH YOU, COULD IT FEEL THE SAME

IT DON’T MATTER WHO YOU ARE
IT IS SO SIMPLE, A FEELING, BUT IT’S EVERYTHING
NO MATTER WHO YOU LOVE
IT IS SO SIMPLE, A FEELING, BUT IT’S EVERYTHING
IMISSYOULYRICS

danceForYouLyrics = <<-DANCEFORYOULYRICS
I JUST WANNA SHOW YOU HOW MUCH I APPRECIATE YOU (YES)
WANNA SHOW YOU HOW MUCH I’M DEDICATED TO YOU (YES) 
WANNA SHOW YOU HOW MUCH I WILL FOREVER BE TRUE (YES) 
WANNA SHOW YOU HOW MUCH YOU GOT YOUR GIRL FEELING GOOD (OH YES)

WANNA SHOW YOU HOW MUCH, HOW MUCH YOU’RE UNDERSTOOD (OH YES)
WANNA SHOW YOU HOW MUCH I VALUE WHAT YOU SAY
NOT ONLY ARE YOU LOYAL, YOU’RE PATIENT WITH ME BABE (OH YES)
I WANNA SHOW YOU HOW MUCH I REALLY CARE ABOUT YOUR HEART 
I WANNA SHOW YOU HOW MUCH I HATE BEING APART (OH YES) 
SHOW YA, SHOW YA, SHOW YA TILL YOU’RE THROUGH WITH ME 
I WANNA KEEP IT HOW IT IS, SO YOU COULD NEVER SAY HOW IT USED TO BE

LOVING YOU, IS REALLY ALL THAT’S ON MY MIND 
AND I CAN’T HELP BUT TO THINK ABOUT IT DAY AND NIGHT 
I WANNA MAKE THAT BODY ROCK, SIT BACK AND WATCH

TONIGHT I’M GONNA DANCE FOR YOU (OHHH)
TONIGHT I’M GONNA DANCE FOR YOU (OHHH) 
TONIGHT I’M GONNA PUT MY BODY ON YOUR BODY, BOY I LIKE IT WHEN YOU WATCH ME
AH, TONIGHT IT’S GOIN’ DOWN

I’LL BE ROCKIN’ ON MY BABE, ROCKIN’, ROCKIN’ ON MY BABE
SWIRLIN’ ON MY BABE, SWIRLIN’, SWIRLIN’ ON MY BABE
BABY LET ME PUT MY BODY ON YOUR BODY, PROMISE NOT TO TELL NOBODY
'CAUSE IT’S BOUT TO GO DOWN


YOU’LL NEVER NEED TWO, ’CAUSE I WILL BE YOUR NUMBER ONE 
THEM OTHER CHICKS ARE SUPERFICIAL, GLAD I KNOW YOU KNOW I’M THE ONE
THAT’S WHY I’M ALL INTO YOU, ’CAUSE I CAN RECOGNIZE THAT YOU KNOW THAT
THAT’S WHY I’M BACKIN’ THIS THING BACK 
POP, POPPIN’ THIS THING BACK, DROP, DROP, DROPPING THIS THING BACK

THIS IS FOR THE TIME YOU GAVE ME FLOWERS, FOR THE WORLD THAT IS OURS 
FOR THE MOOLAH, FOR THE POWER OF LOVE 
AND NO I WON’T NEVER, EVER, EH, EVER GIVE YOU UP
AND I WANNA SAY THANK YOU IN CASE I DON’T THANK YOU ENOUGH 

A WOMAN IN THE STREET AND A FREAK IN THE YOU KNOW WHAT
SIT BACK, SIT BACK IT’S THE PRE-GAME SHOW, DADDY YOU KNOW WHAT’S UP

LOVING YOU, IS REALLY ALL THAT’S ON MY MIND 
AND I CAN’T HELP BUT TO THINK ABOUT IT DAY AND NIGHT
I WANNA MAKE THAT BODY ROCK, SIT BACK AND WATCH

TONIGHT I’M GONNA DANCE FOR YOU (OHHH) 
TONIGHT I’M GONNA DANCE FOR YOU (OHHH) 
TONIGHT I’M GONNA PUT MY BODY ON YOUR BODY, BOY I LIKE IT WHEN YOU WATCH ME
AH, TONIGHT IT’S GOIN’ DOWN

I’LL BE ROCKIN’ ON MY BABE, ROCKIN’, ROCKIN’ ON MY BABE 
I’LL BE SWIRLIN’ ON MY BABE, SWIRLIN’, SWIRLIN’ ON YOU BABE
BABY LET ME PUT MY BODY ON YOUR BODY, PROMISE NOT TO TELL NOBODY
’CAUSE IT’S ABOUT TO GO DOWN

I’M GONNA TAKE THIS TIME TO SHOW YOU HOW MUCH YOU MEAN TO ME 
‘CAUSE YOU ARE ALL I NEED 
NO MONEY CAN EMPHASIZE OR DESCRIBE THE LOVE THAT’S IN BETWEEN THE LINES
BOY LOOK INTO MY EYES

WHILE I’M GRINDING ON YOU, THIS IS BEYOND SEX, I’M HIGH ON YOU 
IF IT’S REAL THEN YOU KNOW HOW I FEEL
ROCKIN’ ON YOU BABE, ROCKIN’, ROCKIN’ ON YOU BABE, SWIRLIN’ ON YOU BABE 
IN MY MIND ALL I CAN THINK ABOUT IS A FRAME FOR OUR FUTURE AND THE PICTURES OF THE PAST 
AND THE CHANCE TO MAKE THIS LOVE LAST, OHHH

TONIGHT I’M GONNA DANCE FOR YOU (OHHH)
TONIGHT I’M GONNA DANCE FOR YOU (OHHH) 
TONIGHT I’M GONNA PUT MY BODY ON YOUR BODY, BOY I LIKE IT WHEN YOU WATCH ME
AH, TONIGHT IT’S GOIN’ DOWN

I’LL BE ROCKIN’ ON MY BABE, ROCKIN’, ROCKIN’ ON MY BABE 
I’LL BE SWIRLIN’ ON MY BABE, SWIRLIN’, SWIRLIN’ ON YOU BABE
I WANNA PUT MY BODY ON YOUR BODY, PROMISE NOT TO TELL NOBODY 
’CAUSE IT’S ABOUT TO GO DOWN

WATCH ME POP IT, POP IT, POP, POP, POP, POP IT FOR YOU BABY
DROP IT, DROP IT, DROP IT, DROP IT FOR YOU BABY
WATCH IT, WATCH IT, WATCH IT, WATCH ME THROW IT BABY
WANNA MAKE THAT BODY ROCK, SIT BACK AND WATCH

ME POP IT, POP IT, POP, POP, POP, POP IT FOR YOU BABY 
DROP IT, DROP IT, DROP IT, DROP IT FOR YOU BABY
WATCH IT, WATCH IT, WATCH IT, WATCH ME THROW IT BABY
WANNA MAKE THAT BODY ROCK, SIT BACK AND WATCH

(OHHH….OHHH…..)
YES, YES, YES, OH YES, OH YES, YES, YES, OH YES
DANCEFORYOULYRICS

iCareLyrics = <<-ICARELYRICS
I TOLD YOU HOW YOU HURT ME BABY, BUT YOU DON’T CARE
NOW I’M CRYING AND DESERTED BABY, BUT YOU DON’T CARE
AIN’T NOBODY TELL ME THIS IS LOVE, WHEN YOU’RE IMMUNE TO ALL MY PAIN 
I NEED YOU TO TELL ME THIS IS LOVE, YOU DON’T CARE WELL THAT’S OK

WELL I CARE
I KNOW YOU DON’T CARE TOO MUCH 
BUT I STILL CARE, LA, LA, LA… BABY, LA, LA, LA…

OH I CARE 
I KNOW YOU DON’T CARE TOO MUCH
BUT I STILL CARE, LA, LA, BABY, LA, LA, LA… OHHH

EVER SINCE YOU KNEW YOUR POWER, YOU MADE ME CRY 
AND NOW EVERY TIME OUR LOVE GOES SOUR, YOU WON’T SYMPATHIZE
YOU SEE THESE TEARS FALLING DOWN TO MY EARS, I SWEAR YOU LIKE WHEN I’M IN PAIN
I TRY TO TELL YOU ALL MY FEARS, YOU STILL DON’T CARE, THAT’S OK

WELL I CARE 
I KNOW YOU DON’T CARE TOO MUCH
BUT I STILL CARE, LA, LA, LA… BABY, LA, LA, LA…

OH I CARE 
I KNOW YOU DON’T CARE TOO MUCH
BUT I STILL CARE, LA, LA, BABY, LA, LA, LA… OHHH

BOY MAYBE IF YOU CARED ENOUGH, I WOULDN’T HAVE TO CARE SO MUCH 
WHAT HAPPENED TO OUR TRUST, NOW YOU’RE JUST GIVIN’ UP 
YOU USED TO BE SO IN LOVE, NOW YOU DON’T CARE NO MORE

OOOOOOOOOOO…

WELL I CARE 
I KNOW YOU DON’T CARE TOO MUCH
BUT I STILL CARE, LA, LA, LA… BABY, LA, LA, LA…

OH I CARE 
I KNOW YOU DON’T CARE TOO MUCH 
BUT I STILL CARE, LA, LA, BABY, LA, LA, LA… OHHH

I STILL CARE (LA, LA, LA….)
I STILL CARE (LA, LA, LA….)
I STILL CARE (LA, LA, LA….)
ICARELYRICS

ratherDieYoungLyrics = <<-RATHERDIEYOUNGLYRICS
BOY YOU’LL BE THE DEATH OF ME
YOU’RE MY JAMES DEAN
YOU MAKE ME FEEL LIKE I’M 17
YOU DRIVE TOO FAST
YOU SMOKE TOO MUCH 
BUT THAT DON’T MEAN A THING 
CAUSE I’M ADDICTED TO THE RUSH

’CAUSE I’D RATHER DIE YOUNG 
THAN LIVE MY LIFE WITHOUT YOU
I’D RATHER NOT LIVE AT ALL
THAN LIVE MY LIFE WITHOUT YOU
(2X)

YOU KNOW I’VE BEEN IN LOVE BEFORE
YOU’RE THE FIRST ONE I EVER SEEN THAT BURNS LIKE GASOLINE
SO LIGHT A MATCH, TURN OFF THE LIGHTS 
I’M HOLDING ONTO YOU, ’CAUSE THIS MIGHT BE OUR LAST NIGHT

’CAUSE I’D RATHER DIE YOUNG
THAN LIVE MY LIFE WITHOUT YOU 
I’D RATHER NOT LIVE AT ALL
THAN LIVE MY LIFE WITHOUT YOU 
(2X)

WHAT I’M TELLING YOU 
I’M GIVING YOU MY LIFE, IT’S IN YOUR HANDS 
AND WHAT I’M GONNA DO
IS BE A WOMAN AND YOU CAN BE A MAN 
AND I WANNA SAY
NOBODY UNDERSTANDS WHAT WE’VE BEEN THROUGH 
I’D RATHER GIVE UP EVERYTHING
THAN TO LIVE MY, LIVE MY LIFE WITHOUT YOU, OHHH, OHHH

’CAUSE I’D RATHER DIE YOUNG
THAN LIVE MY LIFE WITHOUT YOU 
I’D RATHER NOT LIVE AT ALL 
THAN LIVE MY LIFE WITHOUT YOU
(2X)
RATHERDIEYOUNGLYRICS

onePlusOneLyrics = <<-ONEPLUSONELYRICS
IF I AIN’T GOT NOTHING, I GOT YOU
IF I AIN’T GOT SOMETHING I DON’T GIVE A DAMN, ’CAUSE I GOT IT WITH YOU 
I DON’T KNOW MUCH ABOUT ALGEBRA, BUT I KNOW ONE PLUS ONE EQUALS TWO 
AND IT’S ME AND YOU, THAT’S ALL WE'LL HAVE WHEN THE WORLD IS THROUGH

’CAUSE BABY WE AIN’T GOT NOTHING WITHOUT LOVE
DARLING YOU GOT ENOUGH FOR THE BOTH OF US 
SO COME ON BABY
MAKE LOVE TO ME
WHEN MY DAYS LOOK LOW, PULL ME IN CLOSE AND DON’T LET ME GO 
MAKE LOVE TO ME
SO WHEN THE WORLD’S AT WAR, LET OUR LOVE HEAL US ALL
RIGHT NOW BABY
MAKE LOVE TO ME, ME, ME, ME, ME
OHHHH OHHH, MAKE LOVE TO ME

HEY, I DON'T KNOW MUCH ABOUT GUNS BUT I, I’VE BEEN SHOT BY YOU 
HEY, AND I DON'T KNOW WHEN I’M GON’ DIE, BUT I HOPE THAT I’M GON’ DIE BY YOU
HEY, AND I DON’T KNOW MUCH ABOUT FIGHTING BUT I, I KNOW I WILL FIGHT FOR YOU 
HEY, AND JUST WHEN I BALL UP MY FIST I REALIZE THAT I’M LAYING RIGHT NEXT TO YOU

BABY WE AIN’T GOT NOTHING BUT LOVE 
AND DARLING YOU GOT ENOUGH FOR THE BOTH OF US
OHHHH MAKE LOVE TO ME
WHEN MY DAYS LOOK LOW, PULL ME IN CLOSE AND DON’T LET ME GO
MAKE LOVE TO ME 
SO WHEN THE WORLD’S AT WAR, LET OUR LOVE HEAL US ALL 
HELP ME LET DOWN MY GUARD 
MAKE LOVE TO ME, ME, ME, ME, ME
OHHH OHHH, MAKE LOVE TO ME, ME, ME, ME
ONEPLUSONELYRICS

endOfTimeLyrics = <<-ENDOFTIMELYRICS
COME TAKE MY HAND, I WON’T LET YOU GO 
I’LL BE YOUR FRIEND, I WILL LOVE YOU SO DEEPLY 
I WILL BE THE ONE TO KISS YOU AT NIGHT 
I WILL LOVE YOU UNTIL THE END OF TIME

I’LL BE YOUR BABY, I PROMISE NOT TO LET YOU GO 
LOVE YOU LIKE CRAZY, NOW SAY YOU’LL NEVER LET ME GO 
SAY YOU’LL NEVER LET ME GO, SAY, SAY YOU’LL NEVER LET ME GO 
SAY YOU’LL NEVER LET ME GO, SAY, SAY YOU’LL NEVER LET ME GO

TAKE YOU AWAY FROM HERE
THERE’S NOTHING BETWEEN US, BUT SPACE AND TIME 
I’LL BE YOUR OWN LITTLE STAR, LET ME SHINE IN YOUR WORLD 
I’LL BE YOUR OWN LITTLE UNIVERSE, MAKE ME YOUR GIRL

COME TAKE MY TAKE MY HAND, I WON’T LET YOU GO 
I’LL BE YOUR FRIEND, I WILL LOVE YOU SO DEEPLY
I WILL BE THE ONE TO KISS YOU AT NIGHT 
I WILL LOVE YOU UNTIL THE END OF TIME

I’LL BE YOUR BABY, I PROMISE NOT TO LET YOU GO 
LOVE YOU LIKE CRAZY, NOW SAY YOU’LL NEVER LET ME GO
SAY YOU’LL NEVER LET ME GO, SAY, SAY YOU’LL NEVER LET ME GO 
SAY YOU’LL NEVER LET ME GO, SAY, SAY YOU’LL NEVER LET ME GO

BABY COME ON GET UP ON IT, SHOW ME THAT YOU REALLY WANT IT 
I WANNA BE THE ONE TO LOVE YOU BABY LET’S GO, LET’S GO 
I WANNA PROVIDE THIS LOVIN’ THAT YOUR GIVIN’, I AIN’T FRONTIN’ IN THIS LOVE OH
CAN YOU LET ME LOVE YOU FROM YOUR HEAD TO TOE, BABY LET’S GO

BOY COME TO ME (COME TO ME)
LET ME TURN YOUR RAIN INTO SUN (COME TO ME BABY)
YOU DON’T HAVE TO WORRY BABY (OH NO)
I PROMISE I’LL SET YOUR HEART FREE
LET MY LOVE INTO YOUR SOUL, YOU GO, I GO, WE GO, THAT’S ALL SHE WROTE

SAY, SAY YOU’LL NEV, NEVER…..
CAN’T YOU SEE 
I JUST WANNA LOVE YOU
CAN’T YOU FEEL ME BABE
I JUST WANNA BE WITH YOU 
I JUST WANT LIVE FOR YOU 
I’LL NEVER LET YOU GO
BRING YOUR LOVE TO ME

COME TAKE MY TAKE MY HAND, I WON’T LET YOU GO 
I’LL BE YOUR FRIEND, I WILL LOVE YOU SO DEEPLY 
I WILL BE THE ONE TO KISS YOU AT NIGHT 
I WILL LOVE YOU UNTIL THE END OF TIME

I’LL BE YOUR BABY, I PROMISE NOT TO LET YOU GO 
LOVE YOU LIKE CRAZY, NOW SAY YOU’LL NEVER LET ME GO 
SAY YOU’LL NEVER LET ME GO, SAY, SAY YOU’LL NEVER LET ME GO
SAY YOU’LL NEVER LET ME GO, SAY, SAY YOU’LL NEVER LET ME GO
ENDOFTIMELYRICS

runTheWorldLyrics = <<-RUNTHEWORLDLYRICS
GIRLS, WE RUN THIS MUTHA, YEAH (X3)
GIRLS, WE RUN THIS MUTHA, GIRLS 
WHO RUN THE WORLD, GIRLS, (X4)
WHO RUN THIS MUTHA, GIRLS, (X4)
WHO RUN THE WORLD, GIRLS (X4)

SOME OF THEM MEN THINK THEY FREAK THIS LIKE WE DO BUT NO THEY DON’T 
MAKE YO CHECK COME AT THEY NECK, DISRESPECT US NO THEY WON’T
BOY DON’T EVEN TRY TO TOUCH THIS, BOY THIS BEAT IS CRAZY
THIS IS HOW THEY MADE ME, HOUSTON TEXAS BABY

THIS GOES OUT TO ALL MY GIRLS THAT’S IN THE CLUB ROCKIN’ THE LATEST
WHO WILL BUY IT FOR THEMSELVES AND GET MORE MONEY LATER

I THINK I NEED A BARBER, NONE OF THESE CAN FADE ME 
I’M SO GOOD WITH THIS, I REMIND YOU I'M SO HOOD WITH THIS

BOY I’M JUST PLAYIN’
COME HERE BABY 
HOPE YOU STILL LIKE ME
F U PAY ME

MY PERSUASION CAN BUILD A NATION
ENDLESS POWER WITH OUR LOVE WE CAN DEVOUR
YOU'LL DO ANYTHING FOR ME

WHO RUN THE WORLD, GIRLS (X5) 
WHO RUN THIS MUTHA, GIRLS (X4)
WHO RUN THE WORLD, GIRLS (X4)

IT'S HOT UP IN HERE DJ DON’T BE SCARED TO RUN THIS RUN THIS BACK 
I'M REPPIN’ FOR THE GIRLS WHO TAKIN’ OVER THE WORLD
HELP ME RAISE A GLASS FOR THE COLLEGE GRADS

41 ROLLIN’ TO LET YOU KNOW WHAT TIME IT IS, CHECK
YOU CAN’T HOLD ME I WORK MY 9 TO 5 BETTA CUT MY CHECK

THIS GOES OUT TO ALL THE WOMEN GETTIN’ IT IN YOU ON YO GRIND 
TO ALL THE MEN THAT RESPECT WHAT I DO PLEASE ACCEPT MY SHINE

BOY YOU KNOW YOU LOVE IT HOW WE SMART ENOUGH TO MAKE THESE MILLIONS, STRONG ENOUGH TO BARE THE CHILDREN, THEN GET BACK TO BUSINESS

SEE, YOU BETTER NOT PLAY ME
OH COME HERE BABY
HOPE YOU STILL LIKE ME
F U PAY ME

MY PERSUASION CAN BUILD A NATION
EN DLESS POWER WITH OUR LOVE WE CAN DEVOUR
YOU'LL DO ANYTHING FOR ME

WHO RUN THE WORLD, GIRLS (X5) 
WHO RUN THIS MUTHA, GIRLS (X4)
WHO RUN THE WORLD, GIRLS (X4)

WHO ARE WE, WHAT WE RUN, THE WORLD
WHO RUN THIS MUTHA, YEAH 
WHO ARE WE, WHAT WE RUN, THE WORLD
WHO RUN THIS MUTHA, YEAH
WHO ARE WE, WHAT DO WE RUN, WE RUN THE WORLD
WHO RUN THIS MUTHA, YEAH
WHO ARE WE, WHAT WE RUN, WE RUN THE WORLD 
WHO RUN THE WORLD....GIRLS
RUNTHEWORLDLYRICS

bestThingINeverHadLyrics = <<-BTINH
WHAT GOES AROUND, COMES BACK AROUND, HEY, MY BABY
WHAT GOES AROUND, COMES BACK AROUND, HEY, MY BABY, I SAY
WHAT GOES AROUND, COMES BACK AROUND, HEY, MY BABY 
WHAT GOES AROUND, COMES BACK AROUND

THERE WAS A TIME I THOUGHT, THOUGHT YOU DID EVERYTHING RIGHT
NO LIES, NO WRONG, BOY I, MUST HAVE BEEN OUTTA MY MIND 
SO WHEN I THINK OF THE TIME THAT I ALMOST LOVED YOU 
YOU SHOWED YOUR ASS AND I, I SAW THE REAL YOU 
THANK GOD YOU BLEW IT, THANK GOD I DODGED A BULLET 
I’M SO OVER YOU, SO BABY GOOD LOOKIN’ OUT

I WANTED YOU BAD, I’M SO THROUGH WITH THAT 
’CAUSE HONESTLY YOU TURNED OUT TO BE THE BEST THING I NEVER HAD 
YOU TURNED OUT TO BE THE BEST THING I NEVER HAD
AND I’M GON’ ALWAYS BE THE BEST THING YOU NEVER HAD
OH YEAH, I BET IT SUCKS TO BE YOU RIGHT NOW

SO SAD, YOU’RE HURT, BOO HOO, OH DID YOU EXPECT ME TO CARE
YOU DON’T DESERVE MY TEARS, I GUESS THAT’S WHY THEY AIN’T THERE 
WHEN I THINK THAT THERE WAS A TIME THAT I ALMOST LOVED YOU
YOU SHOWED YOUR ASS AND BABY YES I SAW THE REAL YOU
THANK GOD YOU BLEW IT, THANK GOD I DODGED A BULLET 
I’M SO OVER YOU, BABY GOOD LOOKIN’ OUT

I WANTED YOU BAD, I’M SO THROUGH WITH THAT
’CAUSE HONESTLY YOU TURNED OUT TO BE THE BEST THING I NEVER HAD 
I SAID YOU TURNED OUT TO BE THE BEST THING I NEVER HAD 
AND I’LL NEVER BE THE BEST THING YOU NEVER HAD 
OH BABY I BET IT SUCKS TO BE YOU RIGHT NOW

I KNOW YOU WANT ME BACK
IT’S TIME TO FACE THE FACTS THAT I’M THE ONE THAT GOT AWAY 
LORD KNOWS THAT IT WILL TAKE ANOTHER PLACE, ANOTHER TIME, ANOTHER WORLD, ANOTHER LIFE
THANK GOD I FOUND THE GOOD IN GOODBYE

I USED TO WANT YOU SO BAD, I’M SO THROUGH WITH THAT 
’CAUSE HONESTLY YOU TURNED OUT TO BE THE BEST THING I NEVER HAD 
OH YOU TURNED OUT TO BE THE BEST THING I NEVER HAD
AND I WILL ALWAYS BE THE BEST THING YOU NEVER HAD 
OOOH BEST THING YOU NEVER HAD

I USED TO WANT YOU SO BAD, I’M SO THROUGH WITH THAT 
’CAUSE HONESTLY YOU TURNED OUT TO BE THE BEST THING I NEVER HAD 
OH YOU TURNED OUT TO BE THE BEST THING I NEVER HAD 
OOOH I WILL NEVER BE THE BEST THING YOU NEVER HAD
OH BABY, I BET IT SUCKS TO BE YOU RIGHT NOW

WHAT GOES AROUND, COMES BACK AROUND
WHAT GOES AROUND, COMES BACK AROUND
BET IT SUCKS TO BE YOU RIGHT NOW
WHAT GOES AROUND, COMES BACK AROUND 
I BET IT SUCKS TO BE YOU RIGHT NOW
WHAT GOES AROUND, COMES BACK AROUND 
I BET IT SUCKS TO BE YOU RIGHT NOW
BTINH

startOverLyrics = <<-STARTOVERLYRICS
I FEEL WEAK
WE’VE BEEN HERE BEFORE 
’CAUSE I FEEL WE KEEP GOIN’ BACK AND FORTH 
MAYBE IT’S OVER, MAYBE WE’RE THROUGH
BUT I HONESTLY CAN SAY I STILL LOVE YOU

MAYBE WE’VE REACHED THE MOUNTAIN PEAK
AND THERE’S NO MORE LEFT TO CLIMB 
AND MAYBE WE LOST THE MAGIC PIECE
AND WE’RE BOTH TOO BLIND TO FIND

LET’S START OVER
LET’S GIVE LOVE THEIR WINGS 
LET’S START OVER
STOP FIGHTING ’BOUT THE SAME OLD THING

LET’S START OVER
WE CAN’T LET OUR GOOD LOVE DIE
MAYBE WE CAN START ALL OVER
GIVE LOVE ANOTHER LIFE

I CAN SEE THAT WE’RE NOT HAPPY HERE
SO WHY WOULD WE KEEP PRETENDING WHEN THERE’S NOTHING THERE
MAYBE YOU LIKE IT, WELL I DON’T
AND MAYBE YOU’LL SETTLE, WELL I WON’T

MAYBE WE’VE REACHED THE MOUNTAIN PEAK
AND THERE’S NO MORE LEFT TO CLIMB
AND MAYBE WE LOST THE MAGIC PIECE 
AND WE’RE BOTH TOO BLIND TO FIND

LET’S START OVER 
LET’S GIVE LOVE THEIR WINGS 
LET’S START OVER
STOP FIGHTING ’BOUT THE SAME OLD THING

LET’S START OVER 
WE CAN’T LET OUR GOOD LOVE DIE
MAYBE WE CAN START ALL OVER 
AND GIVE LOVE ANOTHER LIFE

I KNOW THAT THIS WILL HURT YOU, I KNOW YOU’LL CRY
I KNOW I CALLED YOU SELFISH, BUT THAT’S A LIE
I FEEL I KNOW WHAT’S BEST FOR US
LET’S

START OVER 
AND LET’S GIVE LOVE THEIR WINGS
LET’S START OVER
I’M TIRED OF FIGHTING ’BOUT THE SAME OLD THING

LET’S START OVER
WE BOTH KNOW THAT THIS LOVE WON’T DIE
MAYBE WE CAN START ALL OVER
AND GIVE LOVE ANOTHER LIFE
STARTOVERLYRICS

iWasHereLyrics = <<-IWASHERELYRICS
I WANNA LEAVE MY FOOTPRINTS ON THE SANDS OF TIME
KNOW THERE WAS SOMETHIN’ THAT, SOMETHIN’ THAT I LEFT BEHIND 
WHEN I LEAVE THIS WORLD, I’LL LEAVE NO REGRETS
LEAVE SOMETHIN’ TO REMEMBER, SO THEY WON’T FORGET

I WAS HERE, I LIVED, I LOVED
I WAS HERE, I DID, I’VE DONE
EVERYTHING THAT I’VE WANTED AND IT WAS MORE THAN I THOUGHT IT WOULD BE 
I WILL LEAVE MY MARK SO EVERYONE WILL KNOW I WAS HERE

I WANNA SAY I LIVED EACH DAY UNTIL I DIE 
AND KNOW THAT I MEANT SOMETHIN’ IN SOMEBODY’S LIFE
THE HEARTS I HAVE TOUCHED, WILL BE THE PROOF THAT I LEAVE
THAT I MADE A DIFFERENCE AND THIS WORLD WILL SEE

I WAS HERE, I LIVED, I LOVED 
I WAS HERE, I DID, I’VE DONE
EVERYTHING THAT I’VE WANTED AND IT WAS MORE THAN I THOUGHT IT WOULD BE 
I WILL LEAVE MY MARK SO EVERYONE WILL KNOW 
I WAS HERE, I LIVED, I LOVED 
I WAS HERE, I DID, I’VE DONE
EVERYTHING THAT I’VE WANTED AND IT WAS MORE THAN I THOUGHT IT WOULD BE 
I WILL LEAVE MY MARK SO EVERYONE WILL KNOW I WAS HERE

I JUST WANT THEM TO KNOW, THAT I GAVE MY ALL, DID MY BEST
BROUGHT SOMEONE SOME HAPPINESS
LEFT THIS WORLD A LITTLE BETTER JUST BECAUSE I WAS HERE

I WAS HERE, I LIVED, I LOVED 
I WAS HERE, I DID, I’VE DONE
EVERYTHING THAT I’VE WANTED AND IT WAS MORE THAN I THOUGHT IT WOULD BE 
I WANNA LEAVE MY MARK SO EVERYONE WILL KNOW 
I WAS HERE, I LIVED, (I LIVED), I LOVED 
I WAS HERE, I DID, (I DID), I’VE DONE 
I WAS HERE, I LIVED, (I LIVED), I LOVED (I LOVED)
I WAS HERE, I DID, I’VE DONE, I WAS HERE
IWASHERELYRICS

# ============== DANGEROUSLY IN LOVE 

crazyInLoveLyrics = <<-CRAZYINLOVELYRICS
YES, SO CRAZY RIGHT NOW
MOST INCREDIBLY, IT'S YOUR GIRL B
IT'S YOUR BOY, YOUNG
HISTORY IN THE MAKIN' PART 2
SO CRAZY RIGHT NOW
I LOOK AND STARE SO DEEP IN YOUR EYES
I TOUCH ON YOU MORE AND MORE EVERY TIME
WHEN YOU LEAVE I'M BEGGIN' YOU NOT TO GO
CALL YOUR NAME TWO, THREE TIMES IN A ROW
SUCH A FUNNY THING FOR ME TO TRY TO EXPLAIN
HOW I'M FEELING AND MY PRIDE IS THE ONE TO BLAME
YEAH, 'CAUSE I KNOW I DON'T UNDERSTAND
JUST HOW YOUR LOVE CAN DO WHAT NO ONE ELSE CAN
GOT ME LOOKIN' SO CRAZY RIGHT NOW
YOUR LOVE GOT ME LOOKIN' SO CRAZY RIGHT NOW
GOT ME LOOKIN' SO CRAZY RIGHT NOW 
YOUR TOUCH GOT ME LOOKIN' SO CRAZY RIGHT NOW 
GOT ME HOPIN’ YOU PAGE ME RIGHT NOW 
YOUR KISS GOT ME HOPIN’ YOU SAVE ME RIGHT NOW
LOOKIN' SO CRAZY IN LOVE, GOT ME LOOKIN', GOT ME LOOKIN' SO CRAZY IN LOVE
WHEN I TALK TO MY FRIENDS SO QUIETLY
WHO HE THINK HE IS
LOOK AT WHAT YOU DID TO ME
TENNIS SHOES DON'T EVEN NEED TO BUY A NEW DRESS
IF YOU AIN'T THERE, AIN'T NOBODY ELSE TO IMPRESS
IT'S THE WAY THAT YOU KNOW WHAT I THOUGHT I KNEW
IT'S THE BEAT THAT MY HEART SKIPS WHEN I'M WITH YOU 
BUT I STILL DON'T UNDERSTAND
JUST HOW YOUR LOVE CAN DO WHAT NO ONE ELSE CAN
GOT ME LOOKIN' SO CRAZY RIGHT NOW
YOUR LOVE GOT ME LOOKIN' SO CRAZY RIGHT NOW
GOT ME LOOKIN' SO CRAZY RIGHT NOW 
YOUR TOUCH GOT ME LOOKIN' SO CRAZY RIGHT NOW 
GOT ME HOPIN’ YOU PAGE ME RIGHT NOW 
YOUR KISS GOT ME HOPIN’ YOU SAVE ME RIGHT NOW
LOOKIN' SO CRAZY IN LOVE, GOT ME LOOKIN', GOT ME LOOKIN' SO CRAZY IN LOVE
I'M WARMED UP NOW, LET'S GO
YOUNG HOV, Y'ALL KNOW WHEN THE FLOW IS LOCO
YOUNG B AND THE R O C, UH OH
OG, BIG HOMIE THE ONE AND ONLY
STICK BONEY BUT THE POCKETS ARE FAT LIKE TONY
SOPRANO THE ROC HANDLE LIKE VAN EXEL
I SHAKE PHONIES MAN, YOU CAN'T GET NEXT TO
A GENUINE ARTICLE, I DO NOT SING THO
I SLING THOUGH, IF ANYTHING I BLING YO
STARR LIKE RINGO, WAR LIKE A GREEN BERET
YOU'RE CRAZY, BRING YOUR WHOLE SET
JAY-Z IN THE RANGE, CRAZY AND DERANGED
THEY CAN'T FIGURE HIM OUT, THEY'RE LIKE, HEY IS HE INSANE
YES SIR I'M CUT FROM A DIFFERENT CLOTH
MY TEXTURE IS THE BEST FUR, I’M CHINCHILLA
I BEEN ILLER THEN CHAIN SMOKERS
HOW YOU THINK I GOT THE NAME HOVA 
I'VE BEEN REALER, THE GAME'S OVA
FALL BACK YOUNG
EVER SINCE I MADE THE CHANGE OVER TO PLATINUM
THE GAME'S BEEN A WRAP - ONE
GOT ME LOOKIN’ SO CRAZY, MY BABY
I'M NOT MYSELF, LATELY I'M FOOLISH, I DON'T DO THIS
I'VE BEEN PLAYIN’ MYSELF, BABY I DON'T CARE 
‘CAUSE YOUR LOVE GOT THE BEST OF ME
AND BABY YOU'RE MAKING A FOOL OF ME
YOU GOT ME SPRUNG AND I DON'T CARE WHO SEES 
‘CAUSE BABY YOU GOT ME, YOU GOT ME SO CRAZY
GOT ME LOOKIN' SO CRAZY RIGHT NOW
YOUR LOVE GOT ME LOOKIN' SO CRAZY RIGHT NOW
GOT ME LOOKIN' SO CRAZY RIGHT NOW 
YOUR TOUCH GOT ME LOOKIN' SO CRAZY RIGHT NOW 
GOT ME HOPIN’ YOU PAGE ME RIGHT NOW 
YOUR KISS GOT ME HOPIN’ YOU SAVE ME RIGHT NOW
LOOKIN' SO CRAZY IN LOVE, GOT ME LOOKIN', GOT ME LOOKIN' SO CRAZY IN LOVE
CRAZYINLOVELYRICS

naughtyGirlLyrics = <<-NAUGHTYGIRLLYRICS
I LOVE TO LOVE YOU BABY
I LOVE TO LOVE YOU BABY
I'M FEELING SEXY
I WANNA HEAR YOU SAY MY NAME, BOY
IF YOU CAN REACH ME
YOU CAN FEEL MY BURNING FLAME
FEELING KINDA NASTY
I JUST MIGHT TAKE YOU HOME WITH ME
BABY, THE MINUTE I FEEL YOUR ENERGY
YOUR VIBE HAS JUST TAKEN OVER ME
START FEELING SO CRAZY, BABE
LATELY, I FEEL THE FUNK COMING OVER ME
I DON'T KNOW WHAT'S GOTTEN INTO ME
THE RHYTHM'S GOT ME FEELING SO CRAZY, BABE
TONIGHT I'LL BE YOUR NAUGHTY GIRL
I'M CALLING ALL MY GIRLS
WE'RE GONNA TURN THIS PARTY OUT
I KNOW YOU WANT MY BODY
TONIGHT I'LL BE YOUR NAUGHTY GIRL
I'M CALLING ALL MY GIRLS
I SEE YOU LOOK ME UP AND DOWN
AND I THINK ABOUT IT
YOU'RE SO SEXY
TONIGHT I AM ALL YOURS, BOY
THE WAY YOUR BODY
MOVES ACROSS THE FLOOR
FEELING KINDA NASTY 
I JUST MIGHT TAKE YOU HOME WITH ME
BABY, THE MINUTE I FEEL YOUR ENERGY
YOUR VIBE HAS JUST TAKEN OVER ME
START FEELING SO CRAZY, BABE
LATELY, I FEEL THE FUNK COMING OVER ME
I DON'T KNOW WHAT'S GOTTEN INTO ME
THE RHYTHM'S GOT ME FEELING SO CRAZY, BABE
TONIGHT I'LL BE YOUR NAUGHTY GIRL
I'M CALLING ALL MY GIRLS
WE'RE GONNA TURN THIS PARTY OUT
I KNOW YOU WANT MY BODY
TONIGHT I'LL BE YOUR NAUGHTY GIRL
I'M CALLING ALL MY GIRLS
I SEE YOU LOOK ME UP AND DOWN
AND I THINK ABOUT IT
I LOVE TO LOVE YOU BABY
I LOVE TO LOVE YOU BABY
I LOVE TO LOVE YOU BABY
I LOVE TO LOVE YOU BABY
TONIGHT I'LL BE YOUR NAUGHTY GIRL
I'M CALLING ALL MY GIRLS
WE'RE GONNA TURN THIS PARTY OUT
I KNOW YOU WANT MY BODY
TONIGHT I'LL BE YOUR NAUGHTY GIRL
I'M CALLING ALL MY GIRLS
I SEE YOU LOOK ME UP AND DOWN
AND I THINK ABOUT IT
AND I THINK ABOUT IT
NAUGHTYGIRLLYRICS

babyBoyLyrics = <<-BABYBOYLYRICS
CERTIFIED QUALITY
A DAT DA GIRL DEM NEED AND DEM NOT STOP CRY WITHOUT APOLOGY
BUCK DEM DA RIGHT WAY – DAT MY POLICY
SEAN PAUL ALONGSIDE BEYONCÉ – NOW HEAR WHAT DA MAN SAY 
DUTTY YEAH, DUTTY YA, DUTTY YEAH, DUTTY YA 
BEYONCE SING IT NOW GIRL 
BABY BOY YOU STAY ON MY MIND
FULFILL MY FANTASIES
I THINK ABOUT YOU ALL THE TIME
I SEE YOU IN MY DREAMS
BABY BOY NOT A DAY GOES BY
WITHOUT MY FANTASIES
I THINK ABOUT YOU ALL THE TIME
I SEE YOU IN MY DREAMS
AH OH MY BABY'S FLY BABY GO
YES NO HURT ME SO GOOD BABY OH
I'M SO WRAPPED UP IN YOUR LOVE LET ME GO
LET ME BREATHE STAY OUT MY FANTASIES
YA READY GIMME DA TING DAT YA READY GET YA LIVE
AND TELL ME ALL ABOUT DA TINGS THAT YOU WILL FANTASIZE
I KNOW YOU DIG DA WAY ME STEP DA WAY ME MAKE MY STRIDE
FOLLOW YOUR FEELINGS BABY GIRL BECAUSE THEY CANNOT BE DENIED
COME CHECK ME IN A NIGHT AND MAKE WE GET IT AMPLIFIED
ME HAVE DA TING TO RUN DA SHIP ‘CAUSE I'M GO SLIP AND I'M GO SLIDE
AND IN THE WORDS OF LOVE I GOT TA GET IT CERTIFIED
BUT I GIVE YOU DA TOUGHEST LONGEST KINDA RIDE – GIRL
BABY BOY YOU STAY ON MY MIND
FULFILL MY FANTASIES
I THINK ABOUT YOU ALL THE TIME
I SEE YOU IN MY DREAMS
BABY BOY NOT A DAY GOES BY
WITHOUT MY FANTASIES
I THINK ABOUT YOU ALL THE TIME
I SEE YOU IN MY DREAMS
PICTURE US DANCIN’ REAL CLOSE IN A DARK DARK CORNER OF A BASEMENT PARTY
EVERY TIME I CLOSE MY EYES IT'S LIKE EVERYONE LEFT BUT YOU AND ME
IN OUR OWN LITTLE WORLD
THE MUSIC IS THE SUN
THE DANCE FLOOR BECOMES THE SEA
FEELS LIKE TRUE PARADISE TO ME
BABY BOY YOU STAY ON MY MIND
FULFILL MY FANTASIES
I THINK ABOUT YOU ALL THE TIME
I SEE YOU IN MY DREAMS
BABY BOY NOT A DAY GOES BY
WITHOUT MY FANTASIES
I THINK ABOUT YOU ALL THE TIME
I SEE YOU IN MY DREAMS
BABY BOY YOU STAY ON MY MIND
BABY BOY YOU ARE SO DAMN FINE
BABY BOY WON'T YOU BE MINE
BABY BOY LET'S CONCEIVE AN ANGEL
BABY BOY LET'S CONCEIVE AN ANGEL
TOP TOP – GIRL
ME AND YOU TOGETHER IS A WRAP DAT – GIRL 
DRIVING AROUND DA TOWN IN YOUR DROP TOP – GIRL
YOU NO STOP SHOCK – GIRL
LITTLE MORE DA DUTTY, WE'LL ROCK DAT WORLD
LITTLE MORE DA DUTTY, WE'LL ROCK DAT WORLD
BABY BOY YOU STAY ON MY MIND
FULFILL MY FANTASIES
I THINK ABOUT YOU ALL THE TIME
I SEE YOU IN MY DREAMS
BABY BOY NOT A DAY GOES BY
WITHOUT MY FANTASIES
I THINK ABOUT YOU ALL THE TIME
I SEE YOU IN MY DREAMS
WE STEPPIN’ IN HOTTER THIS YEAR
WE STEPPIN’ IN HOTTER THIS YEAR
I KNOW YOU GON' LIKE IT
I KNOW YOU GON' LIKE IT
I'M STEPPIN’ UP HOTTER THIS YEAR
I'M STEPPIN’ UP HOTTER THIS YEAR
SO DON'T YOU FIGHT IT
SO DON'T YOU FIGHT IT
BABYBOYLYRICS

hipHopStarLyrics = <<-HIPHOPSTARLYRICS
PURE PLAYERS
PURE PLAYERS
SLOWLY AS SIR LUSCIOUS STEP UP LIKE A Q-DAWG
A-TOWN’S UP, DEUCES DOWN, IT’S THE NEW CALL
AND YOU CAN DIAL 1-888, CUT SOME
I’M YOUR KINKY OPERATOR WHEN YOU WANNA CUT SOME
AIN’T NO DIAL TONES JUST MILESTONES OF PLEASURE TO REACH
TO EACH HIS OWN, I’M A STONE COLD AQUARIAN FREAK
HUMANITARIAN, BARBARIAN BUT UNDER THE SHEETS
IT’S THE PLAYER FROM THE POINT AND YOUR GIRL FROM THE D
ARE YOU INFATUATED WITH ME
I COULD END YOUR CURIOSITY
IF YOU DON'T THINK I'M TOO RUDE
HERE'S YOUR CHANCE TO MAKE YOUR MOVE
I SIT AND WAIT FOR NOBODY
PEOPLE SAY THAT MY 
MY STYLE IS SO CRAZY
I THINK YOU LIKE IT BABY
DO YOU WANT TO GET NASTY
I DARE YOU TO UNDRESS ME
BABY LET ME KNOW IF YOU WANNA ROLL
WITH THIS HIP HOP STAR
BAD BOOTS ON PANTS DOWN LOW
I'M A HIP HOP STAR
BABY LET ME KNOW IF YOU WANNA RIDE
WITH THIS HIP HOP STAR
I'M A ROCK STAR
DO I BLOW YOU AWAY
DO I STIMULATE YOUR MIND
WOULD YOU TASTE MY LOVE IF I GIVE YOU TIME
I HAVE NONE TO WASTE WITH YOU
I GUESS YOU CAN SAY
MY STYLE IS SO CRAZY
I THINK YOU LIKE IT BABY
DO YOU WANT TO GET MESSY
I DARE YOU TO UNDRESS ME
BABY LET ME KNOW IF YOU WANNA ROLL
WITH THIS HIP HOP STAR
BAD BOOTS ON PANTS DOWN LOW
I'M A HIP HOP STAR
BABY LET ME KNOW IF YOU WANNA RIDE
WITH THIS HIP HOP STAR
I'M A ROCK STAR
UNDRESS ME, UNDRESS ME 
COME
COME BABY, UNDRESS ME
TAKE OFF THAT TANK TOP AND PULL OFF THEM DRAWERS
THE GIRLS ALL PAUSE, GOT THEM DRIPPIN' DOWN THEY SUGAR WALLS
AW NAW! GETTING TO THE NAPPY ROOT
KNOCKING BOOTS AND STILETTOS, DAMN I KEEP IT GHETTO
A COOL TYPE OF FELLOW, MELLOW GOT THE GOLD MEDAL
NEVER SETTLE FOR LESS MY ROSE PETAL
TOOEY, TOOEY, TOOEY, TOOEY! SPIT GAME
VENOM TO GET IT UP IN ‘EM, LET ME P POP THAT THANG
FIRST CHECK HER BRAIN TO SEE IF SHE’S SANE
DERANGED OR STRANGE OR CRAZY AS HELL
YOU NEVER CAN TELL THESE DAYS
EVERYBODY GOT A LITTLE RICK JAMES IN THEY VEINS, MAN
THE WAY I FEEL, OH GIRL, I KNOW IT'S 'BOUT TO BE
ME ALL ON YOU AND DAMN GIRL, YOU ALL OVER ME
BABY LET ME KNOW IF YOU WANNA ROLL
WITH THIS HIP HOP STAR
BAD BOOTS ON PANTS DOWN LOW
I'M A ROCK STAR
BABY LET ME KNOW IF YOU WANNA RIDE
WITH THIS HIP HOP STAR
I'M A ROCK STAR
HIPHOPSTARLYRICS

beWithYouLyrics = <<-BEWITHYOULYRICS
OH BABY
OH BABY
OH YEAH…
I LOVE THE WAY YOU MAKE ME FEEL 
IT SLOWS DOWN TIME
COME IN MY BEDROOM 
AND TURN OFF THE LIGHTS
YOU WHISPER SOFTLY IN MY EAR
MAKES ME UNWIND
THE WAY YOU TOUCH ME
LETS ME KNOW YOU'RE MINE
I'D RATHER BE WITH YOU ‘CAUSE I LOVE THE WAY
YOU SCREAM MY NAME
AND THERE'S NO OTHER MAN THAT GIVES ME WHAT I WANT
AND MAKES ME FEEL THIS WAY
I'D RATHER BE WITH YOU ‘CAUSE YOU HUSTLE HARD 
TO TAKE CARE OF ME
I'D RATHER BE WITH YOU 
I KNOW, I'D RATHER BE WITH YOU 
I LOVE THE WAY YOU LOOK AT ME
STARE INTO MY EYES
WHAT DO THEY SAY TO YOU
BOY DON'T BE SHY
TONIGHT'S THE NIGHT YOUR FANTASIES
WILL ALL COME TRUE 
I AM YOUR WOMAN
I BELONG TO YOU
THERE IS NOTHING, I WON'T DO FOR YOU
I KNOW MY SOUL CONNECTED ME TO YOU
I FEEL SO SAFE WHEN I'M ALONE WITH YOU
I'M HOLDING BACK NOTHING, SAVING IT ALL FOR YOU
BABY I LOVE MAKING LOVE TO YOU
IT'S LIKE A HIGH I CAN'T COME DOWN FROM YOU
I'D RATHER BE WITH YOU ‘CAUSE I LOVE THE WAY 
YOU SCREAM MY NAME 
AND THERE'S NO OTHER MAN THAT GIVES ME WHAT I WANT 
AND MAKES ME FEEL THIS WAY 
I'D RATHER BE WITH YOU ‘CAUSE YOU HUSTLE HARD 
TO TAKE CARE OF ME 
I'D RATHER BE WITH YOU
BOY I’D RATHER BE WITH YOU 
I'D RATHER BE WITH YOU
BOY I’D RATHER BE WITH YOU 
I'D RATHER BE WITH YOU, YEAH
BOY I RATHER BE WITH YOU
I'D RATHER BE WITH YOU, YEAH
BOY I RATHER BE WITH YOU 
I'D RATHER BE WITH YOU ‘CAUSE I LOVE THE WAY
YOU SCREAM MY NAME 
AND THERE'S NO OTHER MAN THAT GIVES ME WHAT I WANT
AND MAKES ME FEEL THIS WAY 
I'D RATHER BE WITH YOU ‘CAUSE YOU HUSTLE HARD
TO TAKE CARE OF ME 
I'D RATHER BE WITH YOU
BOY I’D RATHER BE WITH YOU 
I KNOW, I'D RATHER BE WITH YOU 
I'D RATHER BE WITH YOU ‘CAUSE I LOVE THE WAY
YOU SCREAM MY NAME (I AIN’T GOIN’ NOWHERE, I’M HAPPY WITH YOU)
AND THERE'S NO OTHER MAN THAT GIVES ME WHAT I WANT
AND MAKES ME FEEL THIS WAY
I AIN’T THINKIN’ ‘BOUT NOBODY BUT YOU BABY
I’D RATHER BE WITH YOU 
‘CAUSE YOU HUSTLE HARD TO TAKE CARE OF ME
I’D RATHER BE WITH YOU
BOY I’D RATHER BE WITH YOU 
BOY I’D RATHER BE WITH YOU
BEWITHYOULYRICS

meMyselfAndILyrics = <<-MEMYSELFANDILYRICS
ALL THE LADIES IF YOU FEEL ME, HELP ME SING IT OUT
I CAN'T BELIEVE I BELIEVED EVERYTHING WE HAD WOULD LAST
SO YOUNG AND NAIVE OF ME TO THINK SHE WAS FROM YOUR PAST
SILLY OF ME TO DREAM OF ONE DAY HAVING YOUR KIDS
LOVE IS SO BLIND IT FEELS RIGHT WHEN IT'S WRONG
I CAN'T BELIEVE I FELL FOR YOUR SCHEMES; I'M SMARTER THAN THAT
SO DUMB AND NAIVE TO BELIEVE THAT WITH ME, YOU'RE A CHANGED MAN
FOOLISH OF ME TO COMPETE WHEN YOU CHEAT WITH LOOSE WOMEN
IT TOOK ME SOME TIME BUT NOW I MOVED ON 
BECAUSE I REALIZED I'VE GOT
ME, MYSELF AND I
THAT'S ALL I GOT IN THE END
THAT'S WHAT I FOUND OUT 
AND IT AIN'T NO NEED TO CRY
I TOOK A VOW THAT FROM NOW ON
I'M GON' BE MY OWN BEST FRIEND
I'M GON' BE MY OWN BEST FRIEND
SO CONTROLLING TO SAY THAT YOU LOVE ME BUT YOU DON'T
YOUR FAMILY TOLD ME ONE DAY I WOULD SEE IT ON MY OWN
NEXT THING I KNOW I'M DEALING WITH YOUR THREE KIDS IN MY HOME
LOVE IS SO BLIND IT FEELS RIGHT WHEN IT'S WRONG
NOW THAT IT'S OVER, STOP CALLING ME
COME PICK UP YOUR CLOTHES
AIN'T NO NEED TO FRONT LIKE YOU’RE STILL WITH ME
ALL YOUR HOMIES KNOW
EVEN YOUR VERY BEST FRIEND TRIED TO WARN ME ON THE LOW
TOOK ME SOME TIME BUT NOW I AM STRONG 
BECAUSE I REALIZED I'VE GOT
ME, MYSELF AND I
THAT’S ALL I GOT IN THE END
THAT'S WHAT I FOUND OUT 
AND IT AIN'T NO NEED TO CRY
I TOOK A VOW THAT FROM NOW ON
I'M GON' BE MY OWN BEST FRIEND
I'M GON' BE MY OWN BEST FRIEND
I GOT ME, MYSELF AND I
(I KNOW THAT I WILL NEVER DISAPPOINT MYSELF)
I MUST HAVE CRIED A THOUSAND TIMES
(ALL THE LADIES IF YOU FEEL ME, HELP ME SING IT OUT)
I CAN'T REGRET TIME SPENT WITH YOU
(YEAH, YOU HURT ME BUT I LEARNED A LOT ALONG THE WAY)
SO I HAVE VOWED TO MAKE IT THROUGH
(AFTER ALL THE RAIN YOU'LL SEE THE SUN COME OUT AGAIN)
NOW I GOT ME, MYSELF AND I
(I KNOW THAT I WILL NEVER DISAPPOINT MYSELF)
I MUST HAVE CRIED A THOUSAND TIMES
(I'VE CRIED)
(ALL THE LADIES IF YOU FEEL ME, HELP ME SING IT OUT)
I CAN'T REGRET TIME SPENT WITH YOU
(YEAH, YOU HURT ME BUT I LEARNED A LOT ALONG THE WAY)
SO I HAVE VOWED TO MAKE IT THROUGH
(AFTER ALL THE RAIN YOU'LL SEE THE SUN COME OUT AGAIN, YEAH)
I'VE GOT ME, MYSELF AND I
(ME, MYSELF AND I)
I MUST HAVE CRIED A THOUSAND TIMES
(I HAVE CRIED SO MANY TIMES)
I CAN'T REGRET TIME SPENT WITH YOU
(I CAN'T REGRET TIME SPENT WITH YOU)
SO I HAVE VOWED TO MAKE IT THROUGH
(AFTER ALL THE RAIN YOU'LL SEE THE SUN COME OUT AGAIN)
NOW I'VE GOT ME, MYSELF AND I
(I KNOW THAT I WILL NEVER DISAPPOINT MYSELF)
I MUST HAVE CRIED A THOUSAND TIMES
(IF YOU CRIED A THOUSAND TIMES, LADIES, YOU WILL SURVIVE)
I CAN'T REGRET TIME SPENT WITH YOU
(YEAH, YOU HURT ME BUT I LEARNED A LOT ALONG THE WAY)
SO I HAVE VOWED TO MAKE IT THROUGH
(I CAN SEE THE SUNSHINE; I'VE GOT ME, MYSELF AND I)
MEMYSELFANDILYRICS

yesLyrics = <<-YESLYRICS
I SAID YES TO YOUR MAMA AND YES TO YOU DATING ME
YES WE CAN BE TOGETHER BUT YOU GOTTA WAIT FOR ME
THE FIRST TIME I SAY NO, IT'S LIKE I NEVER SAID YES
(IT'S LIKE I NEVER SAY YES)
I SAID YES, WE CAN BE TOGETHER
YES, YOU CAN STAY WITH ME
BUT WHEN I SAY NO NOT TONIGHT, YOU ACTING SO UNGRATEFULLY
THE FIRST TIME I SAY NO, IT’S LIKE I NEVER SAID YES
(IT'S LIKE I NEVER SAY YES)
YOU WAS ON THE WALL
I WAS WITH MY CREW
YOU WAS WATCHING ME BABY
I WAS WATCHING YOU
SLOWLY YOU WALKED OVER
I MAINTAINED MY COOL
YOU SAID HELLO TO ME
I SAID HELLO TO YOU
YOU ASKED ME WHERE I'M FROM
I ASKED YOU WHAT YOU DO
YOU SOMEHOW INTRIGUED ME
I THOUGHT YOU WERE SO COOL
SOMEWHERE BETWEEN HI AND GOODBYE, I FELT SO COMFORTABLE
I FELT LIKE WE COULD TALK ALL NIGHT, SO I GAVE MY NUMBER TO YOU
I SAID YES TO YOUR MAMA AND YES TO YOU DATING ME
YES WE CAN BE TOGETHER, BUT YOU GOTTA WAIT FOR ME
THE FIRST TIME I SAY NO, IT'S LIKE I NEVER SAID YES
(IT'S LIKE I NEVER SAY YES)
I SAID YES WE CAN BE TOGETHER
YES, YOU CAN STAY WITH ME
BUT WHEN I SAY NO NOT TONIGHT, YOU ACTING SO UNGRATEFULLY
THE FIRST TIME I SAY NO, IT'S LIKE I NEVER SAID YES
(IT'S LIKE I NEVER SAY YES)
CERTAINLY YOU CAN CALL ME BABY
I LOVE TO HEAR FROM YOU
YES OF COURSE, YOU CAN COME AND SEE ME BOY
WANNA GET TO KNOW YOU MORE, SURE I'M FEELING YOU
NO BABY, NOT YET, WE CAN'T TAKE THAT NEXT STEP
WHY YOU GETTING SO UPSET, BOY YOU
ACT AS THOUGH I NEVER TOLD YOU YES BEFORE, YOU ARE SO UNGRATEFUL
YOU WAS AT MY HOUSE
I WAS SITTING ON MY COUCH
YOU WAS REALLY BUGGING, SO I TOLD YOU TO GET OUT
I HAVE BEEN MISJUDGING YOU, YOU HAD A LOT OF NERVE - YOU
TOO DAMN OLD TO BE SO IMMATURE, I HOPE YOU LEARNED
YOU SAID I MOVE TOO SLOW, I SHOWED YOU TO THE DOOR
YOU SAID YOU'D CALL ME LATER, I SAID DON'T CALL NO MORE
BUT IT'S COOL IF YOU CAN'T WAIT FOR ME, I'M GLAD YOU LET ME KNOW
‘CAUSE YOU SHOWED ME YOUR TRUE FACE BABY, THE FIRST TIME I SAID NO
I SAID YES TO YOUR MAMA AND YES TO YOU DATING ME
YES, WE CAN BE TOGETHER BUT YOU GOTTA WAIT FOR ME
THE FIRST TIME I SAY NO, IT'S LIKE I NEVER SAID YES
(IT'S LIKE I NEVER SAY YES)
I SAID YES, WE CAN BE TOGETHER
YES, YOU CAN STAY WITH ME
BUT WHEN I SAY NO NOT TONIGHT, YOU ACTING SO UNGRATEFULLY
THE FIRST TIME I SAY NO, IT'S LIKE I NEVER SAID YES
(IT’S LIKE I NEVER SAID YES)
I SAID YES TO YOUR MAMA AND YES TO YOU DATING ME
YES, WE CAN BE TOGETHER BUT YOU GOTTA WAIT FOR ME
THE FIRST TIME I SAY NO, IT'S LIKE I NEVER SAID YES
(IT'S LIKE I NEVER SAID YES)
YESLYRICS

signsLyrics = <<-SIGNSLYRICS
IN DECEMBER EVERY SIGN HAS IT'S OWN MODE
I WAS IN LOVE WITH A SAGITTARIUS
SEE THE EMOTIONS HE PUT ME THROUGH
FROM CAPRICORNS TO AQUARIUS
THEY ALL GOT THEIR DIFFERENT MINDS
THE AFFECTION OF A VIRGO
WHICH SIGN MATCHES GOOD WITH MINE
I WAS IN LOVE WITH A SAGITTARIUS, HE BLEW MY MIND
HE ALSO HAD A FLIP SIDE, TOO MUCH LIKE A GEMINI
HE WAS FREAKY LIKE A TAURUS, THE WAY HE HANDLED ME, YEAH
FLIRTATIOUS LIKE AN ARIES, WHICH SIGN IS BEST FOR ME
CAPRICORN, AQUARIUS, PISCES, ARIES, TAURUS, GEMINI, CANCER, OH
LEO, VIRGO, LIBRA, SCORPIO, SAGITTARIUS, I LOVE ALL Y'ALL
CAPRICORN, AQUARIUS, PISCES, ARIES, TAURUS, GEMINI, CANCER, OH
LEO, VIRGO, LIBRA, SCORPIO, SAGITTARIUS, I LOVE ALL Y'ALL
I WISH HE WAS A VIRGO, THE SAME SIGN AS ME
AND KNOW HOW TO SHOW ME LOVE, ‘CAUSE I'VE BEEN HURT BY A PISCES
REWIND
I WISH HE WAS A VIRGO, THE SAME SIGN AS ME
AND KNOW HOW TO SHOW ME LOVE, ‘CAUSE I'VE BEEN HURT BY A PISCES
I WANT HIM SEXY LIKE A SCORPIO
THE WAY HE HOLDS ME CLOSE, YEAH
SENSITIVE AS A CANCER
EVERY SIGN FROM COAST TO COAST
CAPRICORN, AQUARIUS, PISCES, ARIES, TAURUS, GEMINI, CANCER, OH
LEO, VIRGO, LIBRA, SCORPIO, SAGITTARIUS, I LOVE ALL Y'ALL
CAPRICORN, AQUARIUS, PISCES, ARIES, TAURUS, GEMINI, CANCER, OH
LEO, VIRGO, LIBRA, SCORPIO, SAGITTARIUS, I LOVE ALL Y'ALL
I CAN'T EXPLAIN WHY I LOVE HIM
BOSSY LIKE LEO'S DO
GOT GAME LIKE AN AQUARIUS
SWITCH MOVES AFTER HE BEEN WITH YOU
FUN LIKE A LIBRA
HE STAYS ON MY MIND
HE'S SO UNPREDICTABLE
HE REMINDS ME OF EVERY SIGN
CAPRICORN, AQUARIUS, PISCES, ARIES, TAURUS, GEMINI, CANCER, OH
LEO, VIRGO, LIBRA, SCORPIO, SAGITTARIUS, I LOVE ALL Y'ALL
CAPRICORN, AQUARIUS, PISCES, ARIES, TAURUS, GEMINI, CANCER, OH
LEO, VIRGO, LIBRA, SCORPIO, SAGITTARIUS, I LOVE ALL Y'ALL
EVERY SIGN FROM THE FIRST TO THE LAST
EVERYDAY OF THE MONTH HAS ITS GOOD AND ITS BAD
I LOVE YOU ALL, ALL 12 SIGNS
CAPRICORN, AQUARIUS, PISCES, ARIES, TAURUS, GEMINI, CANCER, OH
CAPRICORN, AQUARIUS, PISCES, ARIES, TAURUS, GEMINI, CANCER, OH
CAPRICORN, AQUARIUS, PISCES, ARIES, TAURUS, GEMINI, CANCER, OH
EVERY ONE OF THESE SIGNS, YOU KNOW YOU’RE BLOWING ME AWAY
NO MATTER WHEN YOU’RE BORN FOR SURE WITH ME, YOU’RE OKAY
I LOVE EVERY ONE OF Y’ALL, NO MATTER WHAT SIGN YOU ARE
JANUARY TO DECEMBER, HERE’S MY OPEN ARMS
I WAS IN LOVE WITH A SAGITTARIUS 
I WAS IN LOVE WITH A SAGITTARIUS
I WAS IN LOVE WITH A SAGITTARIUS
I WAS IN LOVE WITH A SAGITTARIUS
SIGNSLYRICS

speechlessLyrics = <<-SPEECHLESSLYRICS
YOU'VE GOT ME
YOU’VE GOT ME
YOU'VE GOT ME
YOU’VE GOT ME SPEECHLESS
WHERE YOU BEEN LATELY
WAITED FOR YOU ALL DAY
WAITING FOR YOU TO USE THE KEY
THAT OPENS MY PLACE
MY HEART STARTS TREMBLING
AS I HEAR YOUR FOOTSTEPS PACE
LOCK OPENED, DOORKNOB TURNED
THERE APPEARS YOUR FACE
GOING OUT MY HEAD I THINK I’M LOSING ALL MY MIND
DRIVE ME CRAZY, BURNING CANDLES, MAKING LOVE ALL NIGHT
FEEL SO STRANGE, IT FEELS SO CRAZY TO BE IN YOUR WORLD
IN YOUR ARMS, LOST FOR WORDS, YOU'VE GOT ME
YOU'VE GOT ME, YOU'VE GOT ME
YOU'VE GOT ME, YOU'VE GOT ME
YOU’VE GOT ME, YOU’VE GOT ME
YOU’VE GOT ME
SPEECHLESS
LAYING SO CLOSELY
I FEEL YOUR SKIN RUBBING AND TOUCHING ME
ONLY SWEAT BETWEEN US
FEELING YOU KISSING AND PLEASING ME
I RUB YOUR BACK
I KISS YOUR NECK
I KNOW THAT YOU LOVE WHEN WE TOUCH LIKE THAT
I CAN FEEL YOU NEED ME
FEEL SO GOOD TO ME, FEEL SO GOOD TO ME
GOING OUT MY HEAD I THINK I’M LOSING ALL MY MIND
DRIVE ME CRAZY, BURNING CANDLES, MAKING LOVE ALL NIGHT
FEEL SO STRANGE, IT FEELS SO CRAZY TO BE IN YOUR WORLD
IN YOUR ARMS LOST FOR WORDS YOU'VE GOT ME
YOU'VE GOT ME, YOU'VE GOT ME
YOU'VE GOT ME, YOU'VE GOT ME
YOU’VE GOT ME 
SPEECHLESS
YES, YES, YES, YES, YES, YES
SPEECHLESS
ALL I CAN SAY IS…YES, YES, YES, 
ALL I CAN SAY IS…YES, YES, YES
KISS ME
HOLD ME
YOU’VE GOT ME
SPEECHLESS
That's How You Like It
THAT’S HOW YOU LIKE IT, HUH
THAT’S HOW YOU LIKE IT, HUH
THAT’S HOW YOU LIKE IT, HUH
THAT’S HOW I LIKE IT BABY
THAT’S HOW I LIKE IT BABY
THAT’S HOW I LIKE IT BABY
THAT’S HOW I LIKE IT BABY
I NEED A THUG THAT’LL HAVE MY BACK
DO-RAG, NIKE AIRS TO MATCH
AIN’T NOTHIN’ WRONG WITH THAT
THAT’S HOW I LIKE IT, BABY
WHERE MY THUGS AT
WHITE T-SHIRT, I LOVE THAT
TIMBERLAND BOOTS, YOU DOES THAT, IT’S A FACT
THAT’S HOW I LIKE IT, BABY
I LIKE THE WAY YOU WALK
THE WAY YOU TALK
THE WAY YOU DRESS
THE WAY YOU SMILE
I LIKE THE WAY YOU ARE
THE WAY YOU AIN’T
I LIKE YOUR HONESTY, INTEGRITY, IT LEVELS ME
SO PLEASE DON’T EVER CHANGE
THAT’S HOW YOU LIKE IT, HUH
THAT’S HOW YOU LIKE IT, HUH
THAT’S HOW YOU LIKE IT, HUH
THAT’S HOW I LIKE IT BABY
THAT’S HOW I LIKE IT BABY
THAT’S HOW I LIKE IT BABY
THAT’S HOW I LIKE IT BABY
I LIKE THE WAY YOU BRUSH YOUR HAIR
I LIKE THE STYLISH CLOTHES YOU WEAR
IT’S JUST THE REAL THINGS YOU DO
THAT’S WHY I WANNA STICK WITH YOU
WHERE MY GIRLS AT
LET THEM KNOW WE LOVE THAT
SEXY WAY THEY DOES THAT 
THAT’S HOW I LIKE IT BABY
I HOPE YOU LIKE MY STYLE
THE WAY I DRESS
THE WAY I FLIRT
SAY YES
I HOPE YOU LIKE MY MIND
THE THINGS I SAY
IF I’M WITH YOU, THEN I’M WITH ONLY YOU
MY LOYALTY WILL NEVER, EVER CHANGE
THAT’S HOW YOU LIKE IT, HUH
THAT’S HOW YOU LIKE IT, HUH
THAT’S HOW YOU LIKE IT, HUH
THAT’S HOW I LIKE IT BABY
THAT’S HOW I LIKE IT BABY
THAT’S HOW I LIKE IT BABY
THAT’S HOW I LIKE IT BABY
I KNOW YOU’VE HEARD I’M A GANGSTA
THEY SAY STAY AWAY FROM THEM GANGSTAS
THEY NEVER CHANGE UP, OR PULL THEY PANTS UP
WELL, BABY GIRL, PUT YA FOOT DOWN
DON’T LET ‘EM PUSH YOU AROUND, YOU KNOW WHAT YOU LIKE
BABY THUG, YOU KNOW WRONG FROM RIGHT
YOU DONE FELT WRONG BEFORE
THIS CAN’T BE WHAT IT FEEL LIKE
AND THEY DON’T REALLY KNOW WHATCHA FEEL LIKE, FOR INSTANCE
THEY DON’T KNOW THE DIFFERENCE BETWEEN REAL LIFE
AND THE MUSIC VIDEOS AND THE RAGGEDY MAGAZINES
THEY HAVE IT BADDER THAN HE SEEMS
ALL THEY SEE IS MY BAGGY JEANS, MY ATTITUDE
I AIN’T MAD AT YOU, IT’S JUST MY CLYDE
WAY I WEAR MY HAT TO THE SIDE
WAY I LEAN REAL LOW WHEN I RIDE
THAT’S WHY MY MINDS, THEY LIKE MY WALK
MY ACCENT FROM NEW YORK
MY WAY OF THINKING IS SLIGHTLY OFF
THEY LIKE THE WAY HE FLOSS
LEAVE THE BLOCK ON A BIKE, HE COME BACK ON A PORSCHE
BUT OF COURSE
MOST OF ALL, THEY LIKE MY HONESTY, INTEGRITY, MY LOYALTY
YOUNG HOV AND THE LETTER B
HOW YOU LIKE THAT, HUH?
THAT’S HOW YOU LIKE IT, HUH
THAT’S HOW YOU LIKE IT, HUH
THAT’S HOW YOU LIKE IT, HUH
THAT’S HOW I LIKE IT BABY
THAT’S HOW I LIKE IT BABY
THAT’S HOW I LIKE IT BABY
THAT’S HOW I LIKE IT BABY
The Closer I Get to You
THE CLOSER I GET TO YOU
THE MORE YOU MAKE ME SEE
BY GIVING ME ALL YOU’VE GOT (TELL ME MORE)
YOUR LOVE HAS CAPTURED ME
OVER AND OVER AGAIN
I TRIED TO TELL MYSELF THAT WE
COULD NEVER BE MORE THAN FRIENDS
BUT ALL THE WHILE INSIDE I KNEW IT WAS REAL
THE WAY YOU MAKE ME FEEL
LYING HERE NEXT TO YOU
TIME JUST SEEMS TO FLY
NEEDING YOU MORE AND MORE (MORE AND MORE)
LET’S GIVE LOVE A TRY (LET’S GIVE LOVE A TRY)
SWEETER AND SWEETER LOVE GROWS
AND HEAVEN’S THERE FOR THOSE
WHO FOOL THE TRICKS OF TIME
WITH HEARTS OF LOVE WE’LL FIND
TRUE LOVE 
IN A SPECIAL WAY 
THE CLOSER I GET (THE CLOSER I GET TO YOU BABY)
THE MORE YOU MAKE ME SEE (THE MORE YOU MAKE ME SEE)
BY GIVING ME WHAT YOU’VE GOT
YOUR LOVE CAPTURES ME
OVER AND OVER AGAIN
I TRY TO TELL MYSELF THAT WE
COULD NEVER BE MORE THAN FRIENDS 
AND ALL THE WHILE INSIDE I KNEW THIS WAS REAL (GOT TO BE, GOT TO BE REAL)
THE WAY YOU MAKE ME FEEL
MY BABY, MY BABY, MY BABY, MY LOVE (MY LOVE, MY LOVE)
COME A LITTLE CLOSER SO THAT WE CAN SEE INTO THE EYES OF LOVE (I WANNA SEE INTO THOSE EYES OF LOVE)
JUST A LITTLE CLOSER LET ME SPEAK TO YOU, I WANT TO SOFTLY TELL YOU SOMETHING (HERE I AM, HERE’S MY LOVE, I JUST WANT YOU TOO…COME CLOSER LOVE)
COME A LITTLE CLOSER LET ME WHISPER IN YOUR EAR ‘CAUSE I WANNA TELL YOU SOMETHING (I WANNA WHISPER IN YOUR EAR SO SOFT, SO COME CLOSER LOVE)
MOVE ON IN REAL CLOSE SO WE CAN CELEBRATE THE WAY WE FEEL ABOUT EACH OTHER’S LOVING (WANNA TO TELL YOU WORDS, WORDS OF LOVE, WORDS THAT MAKE YOU WANNA)
SPEECHLESSLYRICS

dangerouslyInLoveLyrics = <<-DANGEROUSLYINLOVELYRICS
I LOVE YOU
I LOVE YOU
I LOVE YOU
BABY I LOVE YOU
YOU ARE MY LIFE
MY HAPPIEST MOMENTS WEREN'T COMPLETE
IF YOU WEREN'T BY MY SIDE
YOU'RE MY RELATION
IN CONNECTION TO THE SUN
WITH YOU NEXT TO ME
THERE'S NO DARKNESS I CAN'T OVERCOME
YOU ARE MY RAINDROP
I AM THE SEED
WITH YOU AND GOD, WHO'S MY SUNLIGHT 
I BLOOM AND GROW SO BEAUTIFULLY
BABY, I'M SO PROUD
SO PROUD TO BE YOUR GIRL
YOU MAKE THE CONFUSION
GO ALL AWAY
FROM THIS COLD AND MIXED UP WORLD
I AM IN LOVE WITH YOU
YOU SET ME FREE
I CAN'T DO THIS THING
CALLED LIFE WITHOUT YOU HERE WITH ME
‘CAUSE I'M DANGEROUSLY IN LOVE WITH YOU
I'LL NEVER LEAVE
JUST KEEP LOVING ME
THE WAY I LOVE, YOU LOVING ME
THE WAY I LOVE, YOU LOVING ME
AND I KNOW YOU LOVE ME
LOVE ME FOR WHO I AM
CAUSE YEARS BEFORE I BECAME WHO I AM
BABY YOU WERE MY MAN
I KNOW IT AIN'T EASY
EASY LOVING ME
I APPRECIATE THE LOVE AND DEDICATION
FROM YOU TO ME
LATER ON IN MY DESTINY
I SEE MYSELF HAVING YOUR CHILD
I SEE MYSELF BEING YOUR WIFE
AND I SEE MY WHOLE FUTURE IN YOUR EYES
THOUGHT OF ALL MY LOVE FOR YOU
SOMETIMES MAKE ME WANNA CRY
REALIZE ALL MY BLESSINGS
I'M GRATEFUL TO HAVE YOU BY MY SIDE
I AM IN LOVE WITH YOU
YOU SET ME FREE
I CAN'T DO THIS THING
CALLED LIFE WITHOUT YOU HERE WITH ME
‘CAUSE I'M DANGEROUSLY IN LOVE WITH YOU
I'LL NEVER LEAVE
JUST KEEP LOVING ME
THE WAY I LOVE, YOU LOVING ME
THE WAY I LOVE, YOU LOVING ME
EVERY TIME I SEE YOUR FACE 
MY HEART SMILES
EVERY TIME IT FEELS SO GOOD
IT HURTS SOMETIMES
CREATED IN THIS WORLD
TO LOVE
TO HOLD
TO FEEL
TO BREATHE
TO LOVE YOU
I AM IN LOVE WITH YOU
YOU SET ME FREE
I CAN'T DO THIS THING
CALLED LIFE WITHOUT YOU HERE WITH ME
‘CAUSE I'M DANGEROUSLY IN LOVE WITH YOU
I'LL NEVER LEAVE
JUST KEEP LOVING ME
THE WAY I LOVE, YOU LOVING ME
THE WAY I LOVE, YOU LOVING ME
DANGEROUSLYINLOVELYRICS

beyonceInterludeLyrics = <<-BEYONCEINTERLUDELYRICS
I BELIEVE THAT HARMONIES ARE COLORS
EVERY TIME I PAINT, IT SHARPENS MY HARMONY
YESTERDAY I TRIED TO PAINT YOU, BUT THE COLORS WEREN’T BEAUTIFUL ENOUGH
YOUR LOVE GOES BEYOND WHAT I CAN SAY
LOVE BEYONCÉ
BEYONCEINTERLUDELYRICS

giftFromVirgoLyrics = <<-GIFTFROMVIRGOLYRICS
A GIFT, A GIFT FROM VIRGO 
I WISH I COULD LOOK IN YOUR EYES
AND TELL YOU HOW I FEEL 
RIGHT NOW INSIDE
BABY I KNOW THAT IT'S REAL
SO REAL, SO REAL, SO REAL
HOW I WISH I COULD BE WITH YOU 
HOW I WISH, HOW I WISH, HOW I WISH I COULD BE WITH YOU RIGHT NOW
EVERY MORNING, EVERY AFTERNOON, EVERY NIGHT
I WANNA BE WITH YOU
IT DON'T MATTER IF WE GO TO THE PARK OR WATCH A PLAY
STAY IN THE HOTEL ROOM ALL DAY
I JUST WANNA BE WITH YOU
I LOVE EVERYTHING ABOUT YOU
FROM YOUR OLD SCHOOL TENNIS SHOES
TO THE WAY YOU MOVE WHEN YOU'RE DANCING WITH ME
DO YOU REMEMBER OUR FIRST KISS
IT WASN'T LONG ENOUGH
REMEMBER THE FIRST TIME 
WE SPENT THOSE WEEKS TOGETHER
THEY WERE NOT LONG ENOUGH
ALL OF OUR CONVERSATIONS
ALL OF YOUR SWEET PAGES
THEY'RE NEVER LONG ENOUGH
WHEN IT'S TIME FOR ME TO LEAVE
IT'S SO HARD TO SAY GOOD-BYE
I NEVER WANT TO SAY GOOD-BYE
I NEVER EVER WANT TO SAY GOOD-BYE
ONE DAY, ONE DAY WE'LL MAKE LOVE
FINALLY I’LL BE YOURS
ONLY YOU, ONLY YOU 
I COULD LOVE YOU
IT'S TOO LATE 
I ALREADY LOVE YOU
I LOVE YOU 
I LOVE YOU
I LOVE YOU
GIFTFROMVIRGOLYRICS

daddyLyrics = <<-DADDYLYRICS
I REMEMBER WHEN YOU USE TO TAKE ME ON A BIKE RIDE EVERYDAY ON THE BAYOU 
(YOU REMEMBER THAT? WE WERE INSEPARABLE)
AND I REMEMBER WHEN YOU COULD DO NO WRONG
YOU'D COME HOME FROM WORK AND I JUMPED IN YOUR ARMS WHEN I SAW YOU
I WAS SO HAPPY TO SEE YOU (I WAS SO EXCITED, SO HAPPY TO SEE YOU)
BECAUSE YOU LOVED ME I OVERCOME
AND I'M SO PROUD OF WHAT YOU'VE BECOME
YOU'VE GIVEN ME SUCH SECURITY
NO MATTER WHAT MISTAKES I MAKE, YOU'RE THERE FOR ME
YOU CURE MY DISAPPOINTMENTS AND YOU HEAL MY PAIN
YOU UNDERSTOOD MY FEARS AND YOU PROTECTED ME
TREASURE EVERY IRREPLACEABLE MEMORY AND THAT'S WHY…
I WANT MY UNBORN SON TO BE LIKE MY DADDY
I WANT MY HUSBAND TO BE LIKE MY DADDY
THERE IS NO ONE ELSE LIKE MY DADDY
AND I THANK YOU FOR LOVING ME
I STILL REMEMBER THE EXPRESSION ON YOUR FACE
WHEN YOU FOUND OUT I'D BEEN ON A DATE AND HAD A BOYFRIEND 
(MY FIRST BOYFRIEND, YOU SHOULD HAVE SEEN YOUR FACE)
I STILL REMEMBER I CAUGHT YOU CRYING ‘CAUSE OF MY TATTOO
COULD HAVE SAID BEYONCE I TOLD YOU SO
INSTEAD YOU SAID YOU'D GET ONE TOO 
(EVEN MY MAMA SAID Y'ALL GET ONE JUST LIKE MINE)
WORDS CAN'T EXPRESS MY BOUNDLESS GRATITUDE FOR YOU
I APPRECIATE WHAT YOU DO
YOU'VE GIVEN ME SUCH SECURITY
NO MATTER WHAT MISTAKES, I KNOW YOU'RE THERE FOR ME
YOU CURE MY DISAPPOINTMENTS AND YOU HEAL MY PAIN
YOU UNDERSTAND MY FEARS AND YOU PROTECTED ME
TREASURE EVERY EXTRAORDINARY MEMORY AND THAT'S WHY…
I WANT MY UNBORN SON TO BE LIKE MY DADDY
I WANT MY HUSBAND TO BE LIKE MY DADDY
THERE IS NO ONE ELSE LIKE MY DADDY
AND I THANK YOU FOR LOVING ME
EVEN IF MY MAN BROKE MY HEART TODAY
NO MATTER HOW MUCH PAIN I'M IN, I WILL BE OKAY
CAUSE I GOT A MAN IN MY LIFE THAT CAN'T BE REPLACED
FOR THIS LOVE IS UNCONDITIONAL IT WON'T GO AWAY
I KNOW I'M LUCKY
KNOW IT AIN'T EASY
FOR MEN WHO TAKE CARE OF THEIR RESPONSIBILITIES
LOVE IS OVERWHELMING
LORD WHY DID YOU PICK ME
CAN'T STOP MY TEARS FROM FALLING
I LOVE YOU SO MUCH DADDY
THANK YOU, YOU'VE DONE SO MUCH FOR ME. 
I LOVE YOU DADDY.
I GET SO EMOTIONAL DADDY, EVERY TIME I THINK OF YOU
I GET SO EMOTIONAL DADDY, EVERY TIME I THINK OF YOU
THERE IS NO ONE ELSE LIKE MY DADDY
NO ONE ELSE REPLACE MY DADDY...
DADDYLYRICS

Song.destroy_all
Album.destroy_all

fourAlbum = Album.create(name: "4")

loveOnTop = Song.create!(name: "Love on Top", lyrics: loveOnTopLyrics, album: fourAlbum)
party = Song.create!(name: "Party", lyrics: partyLyrics, album: fourAlbum)
schoolinLife = Song.create!(name: "Schoolin' Life", lyrics: schoolinLifeLyrics, album: fourAlbum)
countdown = Song.create!(name: "Countdown", lyrics: countdownLyrics, album: fourAlbum)
iMissYou = Song.create!(name: "I Miss You", lyrics: iMissYouLyrics, album: fourAlbum)
danceForYou = Song.create!(name: "Dance For You", lyrics: danceForYouLyrics, album: fourAlbum)
iCare = Song.create!(name: "I Care", lyrics: iCareLyrics, album: fourAlbum)
ratherDieYoung = Song.create!(name: "Rather Die Young", lyrics: ratherDieYoungLyrics, album: fourAlbum)
onePlusOne = Song.create!(name: "1+1", lyrics: onePlusOneLyrics, album: fourAlbum)
endOfTime = Song.create!(name: "End of Time", lyrics: endOfTimeLyrics, album: fourAlbum)
runTheWorld = Song.create!(name: "Run the World", lyrics: runTheWorldLyrics, album: fourAlbum)
bestThingINeverHad = Song.create!(name: "Best Thing I Never Had", lyrics: bestThingINeverHadLyrics, album: fourAlbum)
startOver = Song.create!(name: "Start Over", lyrics: startOverLyrics, album: fourAlbum)
iWasHere = Song.create!(name: "I Was Here", lyrics: iWasHereLyrics, album: fourAlbum)


dangerouslyInLove = Album.create(name: "Dangerously In Love")
 # baby boy -  hip hop star
crazyInLove = Song.create!(name: "Crazy In Love", lyrics: crazyInLoveLyrics, album: dangerouslyInLove)
naughtyGirl = Song.create!(name: "Naughty Girl", lyrics: naughtyGirlLyrics, album: dangerouslyInLove)
babyBoy = Song.create!(name: "Baby Boy", lyrics: babyBoyLyrics, album: dangerouslyInLove)
hipHopStar = Song.create!(name: "Hip Hop Star", lyrics: hipHopStarLyrics, album: dangerouslyInLove)
beWithYou = Song.create!(name: "Be With You", lyrics: beWithYouLyrics, album: dangerouslyInLove)
meMyselfAndI = Song.create!(name: "Me, Myself and I", lyrics: meMyselfAndILyrics, album: dangerouslyInLove)
yes = Song.create!(name: "Yes", lyrics: yesLyrics, album: dangerouslyInLove)
signs = Song.create!(name: "Signs", lyrics: signsLyrics, album: dangerouslyInLove)
speechless = Song.create!(name: "Speechless", lyrics: speechlessLyrics, album: dangerouslyInLove)
dangerouslyInLoveSong = Song.create!(name: "Dangerously In Love", lyrics: dangerouslyInLoveLyrics, album: dangerouslyInLove)
beyonceInterlude = Song.create!(name: "Beyonce Interlude", lyrics: beyonceInterludeLyrics, album: dangerouslyInLove)
giftFromVirgo = Song.create!(name: "Gift From Virgo", lyrics: giftFromVirgoLyrics, album: dangerouslyInLove)
daddy = Song.create!(name: "Daddy", lyrics: daddyLyrics, album: dangerouslyInLove)